import type { PeggedAsset } from "./types";

export type { PeggedAsset };

/*
both `name` and `gecko_id` must be included. `name` is used to fetch icon and in API Config. `gecko_id` is used to fetch adapters and prices. 

`description` should be brief but still include: Issuer, function of asset, and asset stablecoin is pegged to.

`mintRedeemDescription` should include brief details on minting and redemption.
*/

export default [
  {
    id: "1",
    name: "Tether", // name is normalized to get icon in frontend
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    symbol: "USDT",
    url: "https://tether.to/",
    description:
      "Launched in 2014, Tether tokens pioneered the stablecoin model. Tether tokens are pegged to real-world currencies on a 1-to-1 basis. This offers traders, merchants and funds a low volatility solution when exiting positions in the market.",
    mintRedeemDescription:
      "Tether customers who have undergone a verification process can exchange USD for USDT and redeem USDT for USD.",
    onCoinGecko: "true",
    gecko_id: "tether", // required: is used as coin's unique id throughout peggedassets-server
    cmcId: "825",
    pegType: "peggedUSD", // must match balance key returned by adapter
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: ["https://tether.to/en/transparency/#reports"],
    twitter: "https://twitter.com/Tether_to",
    wiki: "https://wiki.defillama.com/wiki/USDT",
  },
  {
    id: "2",
    name: "USD Coin",
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    symbol: "USDC",
    url: "https://www.circle.com/usdc/",
    description:
      "USDC is a fully regulated dollar digital stablecoin launched by Circle and Coinbase. USDC is fully backed by cash and short-dated U.S. government obligations, so that it is always redeemable 1:1 for U.S. dollars.",
    mintRedeemDescription:
      "An eligible business can exchange USD for USDC and redeem USDC for USD through a Circle Account.",
    onCoinGecko: "true",
    gecko_id: "usd-coin",
    cmcId: "3408",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: ["https://www.centre.io/usdc-transparency"],
    twitter: "https://twitter.com/circlepay",
    wiki: "https://wiki.defillama.com/wiki/USDC",
  },
  {
    id: "3",
    name: "TerraClassicUSD",
    address: null,
    symbol: "USTC",
    url: "https://www.terra.money/",
    description:
      "Terra is a digital currency. The supply of Terra is adjusted in response to changes in demand to keep its price stable. This is achieved using Luna, the mining token whose stable rewards are designed to absorb volatility from changing economic cycles.",
    mintRedeemDescription:
      "Using Terra Station, $1 worth of LUNA can be burned to mint 1 UST, and vice-versa.",
    onCoinGecko: "true",
    gecko_id: "terrausd",
    cmcId: "7129",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/terra_money",
    wiki: "https://wiki.defillama.com/wiki/UST",
  },
  {
    id: "4",
    name: "Binance USD",
    address: "0x4fabb145d64652a948d72533023f6e7a623c7c53",
    symbol: "BUSD",
    url: "https://www.binance.com/en/busd",
    description:
      "BUSD is a 1:1 USD-backed stablecoin approved by the New York State Department of Financial Services (NYDFS), issued in partnership with Paxos.",
    mintRedeemDescription:
      "Paxos customers who have undergone a verification process can exchange USD for BUSD and redeem BUSD for USD.",
    onCoinGecko: "true",
    gecko_id: "binance-usd",
    cmcId: "4687",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: ["https://paxos.com/attestations/"],
    twitter: "https://twitter.com/PaxosGlobal",
    wiki: "https://wiki.defillama.com/wiki/Binance_USD",
  },
  {
    id: "5",
    name: "Dai",
    address: "0x6b175474e89094c44da98b954eedeac495271d0f",
    symbol: "DAI",
    url: "https://makerdao.com/",
    description:
      "The Dai stablecoin is a decentralized, unbiased, collateral-backed cryptocurrency soft-pegged to the US Dollar. Dai is held in cryptocurrency wallets or within platforms, and is supported on Ethereum and other popular blockchains.",
    mintRedeemDescription:
      "Users mint Dai by depositing accepted collateral assets into Maker Vaults within the Maker Protocol. When the loan is repaid to retrieve the collateral, the paid back Dai is burned.",
    onCoinGecko: "true",
    gecko_id: "dai",
    cmcId: "4943",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/MakerDAO",
    wiki: "https://wiki.defillama.com/wiki/Dai",
  },
  {
    id: "6",
    name: "Frax",
    address: "0x853d955acef822db058eb8505911ed77f175b99e",
    symbol: "FRAX",
    url: "https://frax.finance/",
    description:
      "Frax attempts to be the first stablecoin protocol to implement design principles of both collateralized and algorithmic stablecoins to create a highly scalable, trustless, extremely stable, and ideologically pure on-chain money.",
    mintRedeemDescription:
      "Using the Frax Finance app, FRAX can be minted by locking USDC and burning FXS in a proportion determined by the protocol's collateral ratio.",
    onCoinGecko: "true",
    gecko_id: "frax",
    cmcId: "6952",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/fraxfinance",
    wiki: "https://wiki.defillama.com/wiki/Frax",
  },
  {
    id: "7",
    name: "TrueUSD",
    address: "0x0000000000085d4780b73119b644ae5ecd22b376",
    symbol: "TUSD",
    url: "https://trueusd.com/",
    description:
      "TrueUSD (TUSD) is an independently-verified digital asset redeemable 1-for-1 for US Dollars.",
    mintRedeemDescription:
      "TrueUSD customers who have undergone a verification process can exchange USD for TUSD and redeem TUSD for USD.",
    onCoinGecko: "true",
    gecko_id: "true-usd",
    cmcId: "2563",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: ["https://real-time-attest.trustexplorer.io/truecurrencies"],
    twitter: "https://twitter.com/tusdio",
    wiki: "https://wiki.defillama.com/wiki/TUSD",
  },
  {
    id: "8",
    name: "Liquity USD",
    address: "0x5f98805a4e8be255a32880fdec7f6728c6568ba0",
    symbol: "LUSD",
    url: "https://www.liquity.org/",
    description:
      "Liquity is a decentralized borrowing protocol that allows you to draw interest-free loans against Ether used as collateral. Loans are paid out in LUSD (a USD pegged stablecoin).",
    mintRedeemDescription:
      "Using a Liquity frontend, users mint LUSD by depositing ETH as collateral into a Trove. When the loan is repaid to retrieve the collateral, the paid back LUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "liquity-usd",
    cmcId: "9566",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/LiquityProtocol",
    wiki: "https://wiki.defillama.com/wiki/Liquity",
  },
  {
    id: "9",
    name: "Fei USD",
    address: "0x956f47f50a910163d8bf957cf5846d573e7f87ca",
    symbol: "FEI",
    url: "https://fei.money/",
    description:
      "Fei is a decentralized, scalable, and DeFi-native stablecoin protocol. Fei Protocol's goal is to scalably issue a $1 pegged decentralized stablecoin, FEI.",
    mintRedeemDescription:
      "New FEI is minted via a buy-only bonding curve denominated in ETH. The Fei Protocol deploys its Protocol Controlled Value as liquidity for trading, and FEI is minted or burned to maintain the peg whenever it is traded.",
    onCoinGecko: "true",
    gecko_id: "fei-usd",
    cmcId: "8642",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/feiprotocol",
    wiki: "https://wiki.defillama.com/wiki/FEI",
  },
  {
    id: "10",
    name: "Magic Internet Money",
    address: "0x956f47f50a910163d8bf957cf5846d573e7f87ca",
    symbol: "MIM",
    url: "https://abracadabra.money/",
    description:
      "Abracadabra.money is a lending platform that uses interest-bearing tokens as collateral to borrow a USD pegged stablecoin (Magic Internet Money - MIM), that can be used as any other traditional stablecoin.",
    mintRedeemDescription:
      "Using Abracadabra.money, users mint MIM by depositing interest-bearing tokens as collateral into an Abracadabra cauldron. When the loan is repaid to retrieve the collateral, the paid back MIM is burned.",
    onCoinGecko: "true",
    gecko_id: "magic-internet-money",
    cmcId: "162",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/MIM_Spell",
    wiki: "https://wiki.defillama.com/wiki/MIM",
  },
  {
    id: "11",
    name: "Pax Dollar",
    address: "0x8e870d67f660d95d5be530380d0ec0bd388289e1",
    symbol: "USDP",
    url: "https://paxos.com/usdp/",
    description:
      "USDP is a regulated stablecoin by Paxos that is redeemable one-to-one for US Dollars.",
    mintRedeemDescription:
      "Paxos customers who have undergone a verification process can exchange USD for USDP and redeem USDP for USD.",
    onCoinGecko: "true",
    gecko_id: "paxos-standard",
    cmcId: "3330",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: ["https://paxos.com/attestations/"],
    twitter: "https://twitter.com/paxosglobal",
    wiki: "https://wiki.defillama.com/wiki/USDP",
  },
  {
    id: "12",
    name: "Neutrino USD",
    address: null,
    symbol: "USDN",
    url: "https://neutrino.at/",
    description:
      "Neutrino USD (USDN) is an algorithmic stablecoin pegged to the US dollar and backed by WAVES.",
    mintRedeemDescription:
      "NSBT stakers can mint 1 USDN by burning $1 worth of WAVES, and vice-versa.",
    onCoinGecko: "true",
    gecko_id: "neutrino",
    cmcId: "5068",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/neutrino_proto",
    wiki: "https://wiki.defillama.com/wiki/Neutrino",
  },
  {
    id: "13",
    name: "YUSD Stablecoin",
    address: "avax:0x111111111111ed1d73f860f57b2798b683f2d325",
    symbol: "YUSD",
    url: "https://yeti.finance/",
    description:
      "Yeti Finance is a cross-margin lending protocol on Avalanche that allows users to borrow up to 21x against their portfolio and receive YUSD, an overcollateralized stablecoin.",
    mintRedeemDescription:
      "Using the Yeti Finance app, users mint YUSD by depositing an accepted collateral asset into a Trove. When the loan is repaid to retrieve the collateral, the paid back YUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "yusd-stablecoin",
    cmcId: "19577",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/YetiFinance",
    wiki: "https://wiki.defillama.com/wiki/Yeti_Finance",
  },
  {
    id: "14",
    name: "USDD",
    address: "tron:TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn",
    symbol: "USDD",
    url: "https://usdd.io/",
    description:
      "USDD is a decentralized cryptocurrency issued by the TRON DAO Reserve.",
    mintRedeemDescription:
      "Members of the TRON DAO Reserve (TDR) can mint and issue USDD by staking TRX. $1 worth of TRX can be burned to mint 1 USDD, and vice-versa.",
    onCoinGecko: "true",
    gecko_id: "usdd",
    cmcId: "19891",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "curve",
    auditLinks: ["https://usdd.io/SlowMistAuditReport-USDDTRC20.pdf"],
    twitter: "https://twitter.com/usddio",
    wiki: "https://wiki.defillama.com/wiki/USDD",
  },
  {
    id: "15",
    name: "Dola",
    address: "0x865377367054516e17014ccded1e7d814edc9ce4",
    symbol: "DOLA",
    url: "https://www.inverse.finance/",
    description:
      "DOLA is an over-collateralized stablecoin pegged to the US Dollar.  It can also be used as collateral within the Frontier protocol to achieve high capital efficiency, leverage and native yield.",
    mintRedeemDescription:
      "Using the Frontier Banking app, users mint DOLA by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back DOLA is burned.",
    onCoinGecko: "true",
    gecko_id: "dola-usd",
    cmcId: "19191",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/InverseFinance",
    wiki: "https://wiki.defillama.com/wiki/DOLA",
  },
  {
    id: "16",
    name: "Parrot USD",
    address: "solana:Ea5SjE2Y6yvCeW5dYTn7PYMuW5ikXkvbGdcmSnXeaLjS",
    symbol: "PAI",
    url: "https://parrot.fi/",
    description:
      "PAI is an over-collateralized stablecoin created by the Parrot Protocol on Solana.",
    mintRedeemDescription:
      "Using the Parrot app, users mint PAI by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back PAI is burned.",
    onCoinGecko: "true",
    gecko_id: "parrot-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "birdeye",
    auditLinks: null,
    twitter: "https://twitter.com/gopartyparrot",
    wiki: "https://wiki.defillama.com/wiki/Parrot_USD_(PAI)",
  },
  {
    id: "17",
    name: "HUSD",
    address: "0xdf574c24545e5ffecb9a659c229253d4111d87e1",
    symbol: "HUSD",
    url: "https://www.stcoins.com/",
    description:
      "HUSD is an over-collateralized stablecoin built on the Ethereum, HECO and Tron networks.",
    mintRedeemDescription:
      "Stable Universal customers who have undergone a verification process can exchange USD for HUSD and redeem HUSD for USD.",
    onCoinGecko: "true",
    gecko_id: "husd",
    cmcId: "4779",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/Stablecoin_HUSD",
    wiki: "https://wiki.defillama.com/wiki/HUSD",
  },
  {
    id: "18",
    name: "Nexus USD",
    address: "0x1b84765de8b7566e4ceaf4d0fd3c5af52d3dde4f",
    symbol: "NUSD",
    url: "https://synapseprotocol.com/",
    description:
      'nUSD, or "nexus" USD, is a cross-chain stablecoin fully backed by the nexus stablecoin liquidity pool on Ethereum consisting of DAI, USDC, and USDT.',
    mintRedeemDescription:
      "When a stablecoin is bridged between Synapse-enabled chains, the funds are automatically converted to nUSD, and bridged to the destination chain. Once there, this nUSD can be auto-swapped to that chain's native stablecoins using the local nUSD pool.",
    onCoinGecko: false,
    gecko_id: "nexus-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/SynapseProtocol",
    wiki: "https://wiki.defillama.com/wiki/NUSD",
  },
  {
    id: "19",
    name: "Gemini Dollar",
    address: "0x056fd409e1d7a124bd7017459dfea2f387b6d5cd",
    symbol: "GUSD",
    url: "https://www.gemini.com/dollar",
    description:
      "GUSD is a 1:1 USD-backed stablecoin issued by Gemini. Gemini customers can redeem a GUSD for $1 at Gemini.",
    mintRedeemDescription:
      "Gemini customers who have undergone a verification process can exchange USD for GUSD and redeem GUSD for USD.",
    onCoinGecko: "true",
    gecko_id: "gemini-dollar",
    cmcId: "3306",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: ["https://www.gemini.com/dollar"],
    twitter: "https://twitter.com/gemini",
    wiki: "https://wiki.defillama.com/wiki/GUSD",
  },
  {
    id: "20",
    name: "Alchemix USD",
    address: "0xbc6da0fe9ad5f3b0d58160288917aa56653660e9",
    symbol: "ALUSD",
    url: "https://alchemix.fi/",
    description:
      "alUSD is a yield-backed synthetic stablecoin powered by the Alchemix protocol.",
    mintRedeemDescription:
      "alUSD is minted by depositing an accepted collateral asset into an Alchemix Vault. The collateral is used to generate yield that pays down the alUSD debt. Any alUSD used to repay the loan to retrieve the collateral is burned.",
    onCoinGecko: "true",
    gecko_id: "alchemix-usd",
    cmcId: "8614",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/AlchemixFi",
    wiki: "https://wiki.defillama.com/wiki/Alchemix",
  },
  {
    id: "21",
    name: "flexUSD",
    address: "0xa774ffb4af6b0a91331c084e1aebae6ad535e6f3",
    symbol: "FLEXUSD",
    url: "https://coinflex.com/",
    description:
      "flexUSD is a multi-yield bearing stablecoin on Ethereum and smartBCH.",
    mintRedeemDescription:
      "Using the CoinFLEX app, users swap USDC to mint flexUSD 1:1. flexUSD can be redeemed for USDC 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "flex-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "defillama",
    auditLinks: null,
    twitter: "https://twitter.com/coinflexdotcom",
    wiki: "https://wiki.defillama.com/wiki/flexUSD",
  },
  {
    id: "22",
    name: "sUSD",
    address: "0x57ab1ec28d129707052df4df418d58a2d46d5f51",
    symbol: "SUSD",
    url: "https://synthetix.io/",
    description:
      "Synthetix is a protocol for issuing and trading synthetic assets on Ethereum. Each synthetic asset (or Synth) is an ERC20 token which tracks the price of an external asset; for example each sUSD token tracks the price of the US dollar.",
    mintRedeemDescription:
      "An SNX holder can mint sUSD by locking their SNX as collateral via the Synthetix smart contract. sUSD can be burned to swap to another synthetic asset or to repay the debt to retrieve the collateral.",
    onCoinGecko: "true",
    gecko_id: "nusd",
    cmcId: "2927",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/synthetix_io",
    wiki: "https://wiki.defillama.com/wiki/Synthetix",
  },
  {
    id: "23",
    name: "Origin Dollar",
    address: "0x2a8e1e676ec238d8a992307b495b45b3feaa5e86",
    symbol: "OUSD",
    url: "https://www.ousd.com/",
    description:
      "OUSD is a yield-earning, rebasing stablecoin that is backed 1:1 by other stablecoins like USDT, USDC and DAI.",
    mintRedeemDescription:
      "Using the Origin Dollar app, users swap USDC, USDT, or DAI to mint OUSD 1:1. OUSD can be redeemed for USDC, USDT, or DAI 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "origin-dollar",
    cmcId: "7189",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/originprotocol",
    wiki: "https://wiki.defillama.com/wiki/Origin_Dollar",
  },
  {
    id: "24",
    name: "Celo Dollar",
    address: "celo:0x765de816845861e75a25fca122bb6898b8b1282a",
    symbol: "CUSD",
    url: "https://celo.org/",
    description:
      "Celo Dollars (cUSD) are stablecoins that follow the US Dollar and are native to the Celo blockchain's Reserve system. The Celo Reserve is a system of smart contracts that uses a portfolio of cryptocurrencies to expand and contract the supply cUSD, similar to MakerDAO's lending protocol.",
    mintRedeemDescription:
      "Using the Mento app, $1 worth of CELO can be sent to the CELO reserve to mint 1 cUSD, and 1 cUSD can be burned to receive $1 worth of CELO.",
    onCoinGecko: "true",
    gecko_id: "celo-dollar",
    cmcId: "7236",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "kucoin", // coingecko not accurate
    auditLinks: null,
    twitter: "https://twitter.com/CeloOrg",
    wiki: "https://wiki.defillama.com/wiki/CUSD",
  },
  {
    id: "25",
    name: "Reserve",
    address: "0x196f4727526ea7fb1e17b2071b3d8eaa38486988",
    symbol: "RSV",
    url: "https://reserve.org/",
    description:
      "RSV is backed by a basket of on-chain collateral assets, held by the Reserve Vault smart contract. This basket is comprised of equal parts TUSD, PAX, and USDC.",
    mintRedeemDescription:
      "Using the RSV Portal app, equal parts USDC, TUSD, and PAX can be swapped to mint RSV. RSV can be redeemed for its corresponding basket of assets at any time.",
    onCoinGecko: "true",
    gecko_id: "reserve",
    cmcId: "6727",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/holareserve",
    wiki: "https://wiki.defillama.com/wiki/Reserve_(RSV)",
  },
  {
    id: "26",
    name: "mStable USD",
    address: "0xe2f2a5c287993345a840db3b0845fbc70f5935a5",
    symbol: "MUSD",
    url: "https://mstable.org/",
    description:
      "mUSD is USD-pegged cryptoasset on Ethereum and Polygon backed by a basket of selected USD stablecoins.",
    mintRedeemDescription:
      "Using the mStable app, users can swap an accepted stablecoin to mint mUSD 1:1. mUSD can be redeemed for another stablecoin 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "musd",
    cmcId: "5747",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/mstable_",
    wiki: "https://wiki.defillama.com/wiki/MUSD",
  },
  {
    id: "27",
    name: "USDK",
    address: "0x1c48f86ae57291f7686349f12601910bd8d470bb",
    symbol: "USDK",
    url: "https://www.oklink.com/en",
    description:
      "USDK is a USD-pegged stablecoin, jointly launched by OKLink and Prime Trust, an American Trust company.",
    mintRedeemDescription:
      "OKLink customers who have undergone a verification process can exchange USD for USDK and redeem USDK for USD.",
    onCoinGecko: "true",
    gecko_id: "usdk",
    cmcId: "4064",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: [
      "https://oklinksupport.zendesk.com/hc/zh-hk/categories/360001824211-%E8%B5%84%E9%87%91%E5%AE%A1%E8%AE%A1",
    ],
    twitter: "https://twitter.com/OKLink",
    wiki: "https://wiki.defillama.com/wiki/USDK",
  },
  {
    id: "28",
    name: "Vai",
    address: "bsc:0x4bd17003473389a42daf6a0a729f6fdb328bbbd7",
    symbol: "VAI",
    url: "https://venus.io/",
    description:
      "Vai is Venus Protocol's decentralized synthetic stablecoin that is pegged to USD.",
    mintRedeemDescription:
      "VAI is minted by supplying and locking a single or basket of cryptocurrencies. VAI is exchangeable to all supporting assets, including USD, which can be redeemed directly to your bank account in the Swipe Wallet platform for verified users.",
    onCoinGecko: "true",
    gecko_id: "vai",
    cmcId: "7824",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/VenusProtocol",
    wiki: "https://wiki.defillama.com/wiki/VAI",
  },
  {
    id: "29",
    name: "TOR",
    address: "fantom:0x74e23df9110aa9ea0b6ff2faee01e740ca1c642e",
    symbol: "TOR",
    url: "https://tor.cash/",
    description:
      "TOR is a fully collateralized stablecoin built on the Fantom Opera Chain.",
    mintRedeemDescription:
      "Using the Hector Finance app, users swap DAI to mint TOR 1:1. TOR can be redeemed for DAI 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "tor",
    cmcId: "18105",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/HectorDAO_HEC",
    wiki: "https://wiki.defillama.com/wiki/TOR",
  },
  {
    id: "30",
    name: "Dollar on Chain",
    address: "rsk:0xe700691dA7b9851F2F35f8b8182c69c53CcaD9Db",
    symbol: "DOC",
    url: "https://moneyonchain.com/doc-bitcoin-backed-stablecoin/",
    description:
      "Dollar on Chain an over-collateralized USD-pegged stablecoin backed by rBTC on the RSK Blockchain.",
    mintRedeemDescription:
      "Using the Money On Chain app, users mint DoC by depositing rBTC into a vault. When the loan is repaid to retrieve the collateral, the paid back DoC is burned.",
    onCoinGecko: false,
    gecko_id: "doc",
    cmcId: "7558",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/moneyonchainok",
    wiki: "https://wiki.defillama.com/wiki/DOC",
  },
  {
    id: "31",
    name: "SpiceUSD",
    address: "avax:0xab05b04743e0aeaf9d2ca81e5d3b8385e4bf961e",
    symbol: "USDS",
    url: "https://app.spicetrade.ai/",
    description:
      "Spice USD (Ticker USDS) is a stablecoin soft-pegged to USD in the Spice Protocol on Avalanche.",
    mintRedeemDescription:
      "Using the Spice Trade app, USDS can be minted by locking USDC and burning SPICE in a proportion determined by the protocol's collateral ratio.",
    onCoinGecko: "true",
    gecko_id: "spiceusd",
    cmcId: "20306",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/spicetradeai",
    wiki: "https://wiki.defillama.com/wiki/SpiceUSD_(USDS)",
  },
  {
    id: "32",
    name: "Sperax USD",
    address: "arbitrum:0xd74f5255d557944cf7dd0e45ff521520002d5748",
    symbol: "USDS",
    url: "https://sperax.io/",
    description:
      "Sperax USD (USDs) is a USD-pegged stablecoin that is primarily backed by crypto collateral which generates organic yield for its holders.",
    mintRedeemDescription:
      "Using the Sperax app, USDs can be minted by locking USDC or USDT and burning SPA in a proportion determined by the protocol's collateral ratio.",
    onCoinGecko: "true",
    gecko_id: "sperax-usd",
    cmcId: "17285",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "dexscreener", // does not liquidity on curve
    auditLinks: null,
    twitter: "https://twitter.com/SperaxUSD",
    wiki: "https://wiki.defillama.com/wiki/Sperax_USD_(USDS)",
  },
  {
    id: "33",
    name: "USDP Stablecoin",
    address: "0x1456688345527be1f37e9e627da0837d6f08c925",
    symbol: "USDP",
    url: "https://unit.xyz/",
    description:
      "USDP is a decentralized, unbiased, and fully-backed stablecoin whose value is soft-pegged to US Dollar. USDP runs on the Ethereum, BSC, and Fantom networks.",
    mintRedeemDescription:
      "Using the Unit Protocol app, users mint USDP by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back USDP is burned.",
    onCoinGecko: "true",
    gecko_id: "usdp",
    cmcId: "8886",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/unitprotocol",
    wiki: "https://wiki.defillama.com/wiki/USDP_Stablecoin_(USDP)",
  },
  {
    id: "34",
    name: "USD Balance",
    address: "fantom:0x6fc9383486c163fa48becdec79d6058f984f62ca",
    symbol: "USDB",
    url: "https://www.usdbalance.com/",
    description:
      "USDB is an algorithmic stablecoin that powers the FantOHM OHM fork.",
    mintRedeemDescription:
      "Using the USD Balance app, $1 worth of FHM can be burned to mint 1 USDB.",
    onCoinGecko: "true",
    gecko_id: "usd-balance",
    cmcId: "19224",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "defillama",
    auditLinks: null,
    twitter: "https://twitter.com/USDB_",
    wiki: "https://wiki.defillama.com/wiki/FantOHM",
  },
  {
    id: "35",
    name: "MAI",
    address: "polygon:0xa3fa99a148fa48d14ed51d610c367c61876997f1",
    symbol: "MAI",
    url: "https://www.mai.finance/",
    description:
      "MAI is a USD-pegged stablecoin backed by collateral available on many chains.",
    mintRedeemDescription:
      "Using the Mai Finance app, users mint MAI by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back MAI is burned.",
    onCoinGecko: "true",
    gecko_id: "mimatic",
    cmcId: "10238",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/QiDaoProtocol",
    wiki: "https://wiki.defillama.com/wiki/MAI",
  },
  {
    id: "36",
    name: "Ratio Stable Coin",
    address: "solana:USDrbBQwQbQ2oWHUPfA8QBHcyVxKUq1xHyXsSLKdUq2",
    symbol: "USDR",
    url: "https://ratio.finance/",
    description:
      "USDr is an algorithmically risk-adjusted Collateralized Debt Position. Users can mint USDr using stable yield-bearing assets, starting with stablecoin LP from Saber.",
    mintRedeemDescription:
      "USDr is minted by depositing an accepted collateral asset into Ratio Finance. The collateral is used to generate yield that pays down the USDr debt. Any USDr used to repay the loan to retrieve the collateral is burned.",
    onCoinGecko: "true",
    gecko_id: "ratio-stable-coin",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "birdeye",
    auditLinks: null,
    twitter: "https://twitter.com/ratiofinance",
    wiki: "https://wiki.defillama.com/wiki/USDR",
  },
  {
    id: "37",
    name: "USDJ",
    address: "tron:TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT",
    symbol: "USDJ",
    url: "https://just.network/",
    description:
      "USDJ is a fully collateral-backed USD-pegged stablecoin on Tron.",
    mintRedeemDescription:
      "Using the JustStable app, users mint USDJ by depositing TRX into a vault. When the loan is repaid to retrieve the collateral, the paid back USDJ is burned.",
    onCoinGecko: "true",
    gecko_id: "just-stablecoin",
    cmcId: "5446",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/defi_just",
    wiki: "https://wiki.defillama.com/wiki/USDJ",
  },
  {
    id: "38",
    name: "STBL",
    address: "algorand:465865291",
    symbol: "STBL",
    url: "https://www.algofi.org/",
    description:
      "STBL is an algorithmic over-collateralized stablecoin that is native to the Algofi protocol.",
    mintRedeemDescription:
      "Using the Algofi app, users mint STBL by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back STBL is burned.",
    onCoinGecko: false,
    gecko_id: "stbl",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/algofiorg",
    wiki: "https://wiki.defillama.com/wiki/Algofi",
  },
  {
    id: "39",
    name: "VOLT Protocol",
    address: "0x559ebc30b0e58a45cc9ff573f77ef1e5eb1b3e18",
    symbol: "VOLT",
    url: "https://www.voltprotocol.io/",
    description:
      "VOLT is a stablecoin that uses a custom oracle system to stay pegged to the purchasing power of the US Dollar.",
    mintRedeemDescription:
      "Using the Volt Protocol app, users swap FEI or USDC to mint VOLT at the current exchange rate. VOLT can be redeemed for FEI or USDC at any time.",
    onCoinGecko: "true",
    gecko_id: "volt-protocol",
    cmcId: null,
    pegType: "peggedVAR",
    pegMechanism: "algorithmic",
    priceSource: "defillama", // curve has no liqudity, and coingecko not giving accurate price
    auditLinks: null,
    twitter: "https://twitter.com/voltprotocol",
    wiki: "https://wiki.defillama.com/wiki/Volt_Protocol",
  },
  {
    id: "40",
    name: "Rai Reflex Index",
    address: "0x03ab458634910aad20ef5f1c8ee96f1d6ac54919",
    symbol: "RAI",
    url: "https://reflexer.finance/",
    description:
      "RAI is a collateralized, non-pegged asset with low volatility compared to its ETH collateral.",
    mintRedeemDescription:
      "Users mint RAI by depositing ETH as collateral into Rai safes. When the loan is repaid to retrieve the collateral, the paid back RAI is burned.",
    onCoinGecko: "true",
    gecko_id: "rai",
    cmcId: "8525",
    pegType: "peggedVAR",
    pegMechanism: "crypto-backed",
    priceSource: "chainlink",
    auditLinks: null,
    twitter: "https://twitter.com/reflexerfinance",
    wiki: "https://wiki.defillama.com/wiki/RAI",
  },
  {
    id: "41",
    name: "Float Protocol Float",
    address: "0xb05097849bca421a3f51b249ba6cca4af4b97cb9",
    symbol: "FLOAT",
    url: "https://floatprotocol.com/",
    description:
      "FLOAT is a stablecoin that tracks a basket of crypto assets instead of trying to exactly match the price of a dollar.",
    mintRedeemDescription:
      "If the price of FLOAT is away from its target price, the supply is changed by minting (expansion) or buying up and burning FLOAT (contraction). This is done through a dutch auction (in an expansion) and a reverse dutch auction (in a contraction), respectively.",
    onCoinGecko: "true",
    gecko_id: "float-protocol-float",
    cmcId: "9861",
    pegType: "peggedVAR",
    pegMechanism: "algorithmic",
    priceSource: "coingecko", // has low liquidity Uni pool. had pools on dexscreener but they rugged. coingecko is not updating.
    auditLinks: null,
    twitter: "https://twitter.com/FloatProtocol",
    wiki: "https://wiki.defillama.com/wiki/Float_Protocol",
  },
  {
    id: "42",
    name: "USDX",
    address: null,
    symbol: "USDX",
    url: "https://www.kava.io/",
    description:
      "USDX is the crypto-backed native stablecoin of the Kava DeFi hub.",
    mintRedeemDescription:
      "Using the Kava app, users mint USDX by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back USDX is burned.",
    onCoinGecko: "true",
    gecko_id: "usdx",
    cmcId: "6651",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/kava_platform",
    wiki: "https://wiki.defillama.com/wiki/USDX",
  },
  {
    id: "43",
    name: "ZUSD",
    address: "0xc56c2b7e71b54d38aab6d52e94a04cbfa8f604fa",
    symbol: "ZUSD",
    url: "https://stablecoin.z.com/zusd/",
    description:
      "ZUSD is a 100% fiat-backed USD-pegged stablecoin on Ethereum that is always redeemable 1:1.",
    mintRedeemDescription:
      "GMO-Z.com Trust Company customers who have undergone a verification process can exchange USD for ZUSD and redeem ZUSD for USD.",
    onCoinGecko: "true",
    gecko_id: "zusd",
    cmcId: "8772",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: null, // coingecko inaccurate
    auditLinks: ["https://stablecoin.z.com/attestation/"],
    twitter: "https://twitter.com/GMOTrust",
    wiki: "https://wiki.defillama.com/wiki/ZUSD",
  },
  {
    id: "44",
    name: "dForce USD",
    address: "0x0a5E677a6A24b2F1A2Bf4F3bFfC443231d2fDEc8",
    symbol: "USX",
    url: "https://dforce.network/",
    description:
      "USX is a USD-pegged stablecoin by dForce with a dual model for minting - USX can be minted through Vault (single collateral & risk-isolated), or via borrowing from supported lending protocols (pool-based & multi-collateral & market-driven rates) directly.",
    mintRedeemDescription:
      "Using the dForce Network app, users mint USX by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back USX is burned. Users can borrow USX from whitelisted lending protocols which have had their USX liquidity issued algorithmically.",
    onCoinGecko: "true",
    gecko_id: "token-dforce-usd",
    cmcId: "13080",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/dForcenet",
    wiki: "https://wiki.defillama.com/wiki/USX",
  },
  {
    id: "45",
    name: "Acala Dollar",
    address: null,
    symbol: "AUSD",
    url: "https://acala.network/",
    description:
      "aUSD is the native decentralized stablecoin of Polkadot pegged to the US Dollar and backed only by decentralized assets in Collateralized Debt Positions (CDP).",
    mintRedeemDescription:
      "Using the Acala app, users mint aUSD by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back aUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "acala-dollar",
    cmcId: "20411",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko", // coingecko inaccurate
    auditLinks: null,
    twitter: "https://twitter.com/AcalaNetwork",
    wiki: "https://wiki.defillama.com/wiki/Acala",
  },
  {
    id: "46",
    name: "USD+",
    address: "polygon:0x236eec6359fb44cce8f97e99387aa7f8cd5cde1f",
    symbol: "USD+",
    url: "https://overnight.fi/",
    description:
      "USD+ is USDC that pays yield daily via rebase. The USD+ stablecoin can be instantly minted and redeemed to USDC 1:1.",
    mintRedeemDescription:
      "Using the Overnight app, users swap USDC to mint USD+ 1:1. USD+ can be redeemed for USDC 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "usd",
    cmcId: "20317",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "defillama", // for all dexscreener pools with high liquidity, dexscreener api does not give their liquidity.
    auditLinks: null,
    twitter: "https://twitter.com/overnight_fi",
    wiki: "https://wiki.defillama.com/wiki/Overnight",
  },
  {
    id: "47",
    name: "DEI",
    address: "fantom:0xde12c7959e1a72bbe8a5f7a1dc8f8eef9ab011b3",
    symbol: "DEI",
    url: "https://deus.finance/",
    description:
      "DEI is a fractional reserve USD-pegged stablecoin and is the unit of account for all trading within the DEUS Finance ecosystem.",
    mintRedeemDescription:
      "Using the Deus Finance app, DEI can be minted by locking USDC and burning DEUS in a proportion determined by the protocol's collateral ratio.",
    onCoinGecko: "true",
    gecko_id: "dei-token",
    cmcId: "12517",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "dexscreener",
    auditLinks: null,
    twitter: "https://twitter.com/DeusDao",
    wiki: "https://wiki.defillama.com/wiki/Deus_Finance",
  },
  {
    id: "48",
    name: "BAI Stablecoin",
    address: "astar:0x733ebcc6df85f8266349defd0980f8ced9b45f35",
    symbol: "BAI",
    url: "https://astriddao.xyz/",
    description:
      "AstridDAO is a decentralized borrowing protocol on Astar that allows you to draw interest-free loans against multiple collateral assets (e.g. ASTR, ETH, BTC, and etc.). Loans are paid out in BAI (a USD pegged stablecoin).",
    mintRedeemDescription:
      "Using the AstridDAO app, users mint BAI by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back BAI is burned.",
    onCoinGecko: "true",
    gecko_id: "bai-stablecoin",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "dexscreener",
    auditLinks: null,
    twitter: "https://twitter.com/AstridDAO",
    wiki: "https://wiki.defillama.com/wiki/AstridDAO",
  },
  {
    id: "49",
    name: "Euro Tether",
    address: "0xc581b735a1688071a1746c968e0798d642ede491",
    symbol: "EURT",
    url: "https://tether.to/",
    description:
      "Launched in 2014, Tether tokens pioneered the stablecoin model. Tether tokens are pegged to real-world currencies on a 1-to-1 basis. This offers traders, merchants and funds a low volatility solution when exiting positions in the market.",
    mintRedeemDescription:
      "Tether customers who have undergone a verification process can exchange EUR for EURT and redeem EURT for EUR.",
    onCoinGecko: "true",
    gecko_id: "tether-eurt",
    cmcId: "10789",
    pegType: "peggedEUR",
    pegMechanism: "fiat-backed",
    priceSource: "chainlink",
    auditLinks: ["https://tether.to/en/transparency/#reports"],
    twitter: "https://twitter.com/Tether_to",
    wiki: "https://wiki.defillama.com/wiki/EURT",
  },
  {
    id: "50",
    name: "Euro Coin",
    address: "0x1abaea1f7c830bd89acc67ec4af516284b1bc33c",
    symbol: "EUROC",
    url: "https://www.circle.com/",
    description:
      "Euro Coin (EUROC) is issued by Circle under the same full-reserve model as USD Coin (USDC). Euro Coin is 100% backed by euros held in euro-denominated banking accounts so that it's always redeemable 1:1 for euros.",
    mintRedeemDescription:
      "An eligible business can exchange EUR for EUROC and redeem EUROC for EUR through a Circle Account.",
    onCoinGecko: "true",
    gecko_id: "euro-coin",
    cmcId: "20641",
    pegType: "peggedEUR",
    pegMechanism: "fiat-backed",
    priceSource: "curve",
    auditLinks: ["https://www.centre.io/usdc-transparency"],
    twitter: "https://twitter.com/circlepay",
    wiki: "https://wiki.defillama.com/wiki/EUROC",
  },
  {
    id: "51",
    name: "Stasis Euro",
    address: "0xdb25f211ab05b1c97d595516f45794528a807ad8",
    symbol: "EURS",
    url: "https://stasis.net/",
    description: "EURS, an ERC/EIP20 token, is a euro-backed digital asset.",
    mintRedeemDescription:
      "Stasis customers who have undergone a verification process can exchange EUR for EURS and redeem EURS for EUR.",
    onCoinGecko: "true",
    gecko_id: "stasis-eurs",
    cmcId: "2989",
    pegType: "peggedEUR",
    pegMechanism: "fiat-backed",
    priceSource: "curve",
    auditLinks: ["https://stasis.net/transparency"],
    twitter: "https://twitter.com/stasisnet",
    wiki: "https://wiki.defillama.com/wiki/EURS",
  },
  {
    id: "52",
    name: "Celo Euro",
    address: "celo:0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73",
    symbol: "CEUR",
    url: "https://celo.org/",
    description:
      "Celo Euros (cEUR) are stablecoins that follow the Euro and are native to the Celo blockchain's Reserve system. The Celo Reserve is a system of smart contracts that uses a portfolio of cryptocurrencies to expand and contract the supply cEUR, similar to MakerDAO's lending protocol.",
    mintRedeemDescription:
      "Using the Mento app, 1 Euro worth of CELO can be sent to the CELO reserve to mint 1 cEUR, and 1 cEUR can be burned to receive 1 Euro worth of CELO.",
    onCoinGecko: "true",
    gecko_id: "celo-euro",
    cmcId: "9467",
    pegType: "peggedEUR",
    pegMechanism: "algorithmic",
    priceSource: "kucoin",
    auditLinks: null,
    twitter: "https://twitter.com/CeloOrg",
    wiki: "https://wiki.defillama.com/wiki/CEUR",
  },
  {
    id: "53",
    name: "sEUR",
    address: "0xd71ecff9342a5ced620049e616c5035f1db98620",
    symbol: "SEUR",
    url: "https://synthetix.io/",
    description:
      "Synthetix is a protocol for issuing and trading synthetic assets on Ethereum. Each synthetic asset (or Synth) is an ERC20 token which tracks the price of an external asset; for example each sEUR token tracks the price of the Euro.",
    mintRedeemDescription:
      "An SNX holder can mint sEUR by locking their SNX as collateral via the Synthetix smart contract. sEUR can be burned to swap to another synthetic asset or to repay the debt to retrieve the collateral.",
    onCoinGecko: "true",
    gecko_id: "seur",
    cmcId: "10419",
    pegType: "peggedEUR",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/synthetix_io",
    wiki: "https://wiki.defillama.com/wiki/Synthetix",
  },
  {
    id: "54",
    name: "USN",
    address: null,
    symbol: "USN",
    url: "https://decentral-bank.finance/",
    description: "USN is a NEAR-native stablecoin.",
    mintRedeemDescription:
      "Using the Decentral Bank app, users swap USDT to mint USN 1:1. USN can be redeemed for USDT 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "usn",
    cmcId: "19682",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/DcntrlBank",
    wiki: "https://wiki.defillama.com/wiki/USN",
  },
  {
    id: "55",
    name: "agEUR",
    address: "0x1a7e4e63778b4f12a199c062f3efdd288afcbce8",
    symbol: "AGEUR",
    url: "https://www.angle.money/",
    description:
      "Angle Protocol aims at creating a sustainable money layer for blockchains. It is currently issuing agEUR, the most liquid Euro stablecoin on Ethereum and other chains.",
    mintRedeemDescription:
      "Using the Angle app, users mint agEUR by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back agEUR is burned.",
    onCoinGecko: "true",
    gecko_id: "ageur",
    cmcId: "15024",
    pegType: "peggedEUR",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/AngleProtocol",
    wiki: "https://wiki.defillama.com/wiki/AGEUR",
  },
  {
    id: "56",
    name: "Parallel",
    address: "0x68037790a0229e9ce6eaa8a99ea92964106c4703",
    symbol: "PAR",
    url: "https://mimo.capital/",
    description:
      "The PAR token is a price-stable token pegged to the Euro. Users generate PAR by depositing collateral assets into MIMO vaults within the MIMO protocol.",
    mintRedeemDescription:
      "Using the MIMO app, users mint PAR by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back PAR is burned.",
    onCoinGecko: "true",
    gecko_id: "par-stablecoin",
    cmcId: "8665",
    pegType: "peggedEUR",
    pegMechanism: "crypto-backed",
    priceSource: "dexscreener",
    auditLinks: null,
    twitter: "https://twitter.com/mimodefi",
    wiki: "https://wiki.defillama.com/wiki/PAR",
  },
  {
    id: "57",
    name: "Hedge USD",
    address: "solana:9iLH8T7zoWhY7sBmj1WK9ENbWdS1nL8n9wAxaeRitTa6",
    symbol: "USH",
    url: "https://www.hedge.so/",
    description:
      "Hedge is a protocol that enables the minting of USH, a stablecoin soft-pegged to the US dollar. USH is minted on flexible terms and gives users instant access to the USH ecosystem.",
    mintRedeemDescription:
      "Using the Hedge app, users mint USH by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back USH is burned.",
    onCoinGecko: "true",
    gecko_id: "hedge-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "birdeye",
    auditLinks: null,
    twitter: "https://twitter.com/HedgeLabs",
    wiki: "https://wiki.defillama.com/wiki/USH",
  },
  {
    id: "58",
    name: "3USD",
    address: "karura:9iLH8T7zoWhY7sBmj1WK9ENbWdS1nL8n9wAxaeRitTa6",
    symbol: "3USD",
    url: "https://www.taigaprotocol.io/",
    description:
      "3pool on Karura made of aUSD, USDC, USDT is the first stablecoin pool powering the Kusama ecosystem. Liquidity providers will get 3USD token after adding liquidity.",
    mintRedeemDescription:
      "Using the Karura app, users receive 3USD LP tokens by adding aUSD, USDC, or USDT liquidity. LP tokens can be redeemed for the underlying assets.",
    onCoinGecko: "false",
    gecko_id: "three-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/TaigaProtocol",
    wiki: "https://wiki.defillama.com/wiki/Taiga_Protocol",
  },
  {
    id: "59",
    name: "SigmaUSD",
    address: null,
    symbol: "SIGUSD",
    url: "https://sigmausd.io/",
    description:
      "SigmaUSD is a UTxO-based stable coin on the Ergo blockchain - an instantiation of the AgeUSD protocol.",
    mintRedeemDescription:
      "Using the SigmaUSD app, users swap ERG for the equivalent value of SigUSD. The SigUSD is backed by collateral ERG provided by Reserve Providers at a reserve ratio of 400% - 800%.",
    onCoinGecko: "false",
    gecko_id: "sigmausd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/ergoplatformorg",
    wiki: "https://wiki.defillama.com/wiki/Ergo",
  },
  {
    id: "60",
    name: "HomeCoin",
    address: "0xb8919522331c59f5c16bdfaa6a121a6e03a91f62",
    symbol: "HOME",
    url: "https://www.homecoin.finance/",
    description: "A stablecoin backed by U.S. Homes.",
    mintRedeemDescription:
      "Using the Bacon app, users swap USDC to mint HOME 1:1. HOME can be redeemed for USDC 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "bacon-protocol-home",
    cmcId: "20520",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/homecoinfinance",
    wiki: "https://wiki.defillama.com/wiki/HomeCoin",
  },
  {
    id: "61",
    name: "Fixed Income Asset Token",
    address: "0x586Aa273F262909EEF8fA02d90Ab65F5015e0516",
    symbol: "FIAT",
    url: "https://fiatdao.com/",
    description:
      "The FIAT protocol allows users to mint a single ERC-20 token, $FIAT, against a universe of accepted fixed income asset collateral.",
    mintRedeemDescription:
      "Using the FIAT DAO app, users by depositing an accepted fixed income collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back FIAT is burned.",
    onCoinGecko: "true",
    gecko_id: "fixed-income-asset-token",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/fiatdao",
    wiki: "https://wiki.defillama.com/wiki/FIATDAO",
  },
  {
    id: "62",
    name: "PUSd",
    address: "0x466a756e9a7401b5e2444a3fcb3c2c12fbea0a54",
    symbol: "PUSD",
    url: "https://jpegd.io/",
    description:
      "PUSd is a synthetic stablecoin minted against NFT collateralized debt positions.",
    mintRedeemDescription:
      "Using the JPEG'd app, users mint PUSd by depositing an accepted NFT into a vault. When the loan is repaid to retrieve the NFT, the paid back PUSd is burned.",
    onCoinGecko: "true",
    gecko_id: "pusd-2",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/JPEGd_69",
    wiki: "https://wiki.defillama.com/wiki/JPEGd",
  },
  {
    id: "63",
    name: "Fantom USD",
    address: "fantom:0xad84341756bf337f5a0164515b1f6f993d194e1f",
    symbol: "FUSD",
    url: "https://fantom.foundation/defi/",
    description: "fMint is the gateway to Fantom DeFi.",
    mintRedeemDescription:
      "Mint fUSD, the stablecoin on Fantom pegged 1:1 to the USD price, using your FTM. Choose the amount you want to mint and rebalance at any time by adding or removing FTM. Repay the fUSD you minted at any time, unlocking your FTM.",
    onCoinGecko: "true",
    gecko_id: "fantom-usd",
    cmcId: "16831",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "dexscreener",
    auditLinks: null,
    twitter: "https://twitter.com/fantomfdn/",
    wiki: "https://wiki.defillama.com/wiki/Fantom",
  },
  {
    id: "64",
    name: "UXD Stablecoin",
    address: "solana:7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT",
    symbol: "UXD",
    url: "https://uxd.fi/",
    description:
      "UXD Protocol is a fully collateralized decentralized stablecoin on Solana backed by delta-neutral position using derivatives.",
    mintRedeemDescription:
      "Using the UXD Protocol app, users mint UXD by depositing SOL into the protocol where it establishes a derivatives trading position on decentralized exchanges. When the loan is repaid to retrieve the collateral SOL, the paid back UXD is burned.",
    onCoinGecko: "true",
    gecko_id: "uxd-stablecoin",
    cmcId: "17535",
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "birdeye",
    auditLinks: null,
    twitter: "https://twitter.com/UXDProtocol",
    wiki: "https://wiki.defillama.com/wiki/UXD_Protocol",
  },
  {
    id: "65",
    name: "USDH",
    address: "solana:USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX",
    symbol: "USDH",
    url: "https://hubbleprotocol.io/",
    description:
      "USDH is a censorship-resistant, crypto-backed stablecoin on Solana, soft-pegged to the US Dollar. USDH is fully collateralized by a basket of crypto assets, deposited into a Hubble Smart Contract.",
    mintRedeemDescription:
      "Using the Hubble Protocol app, users mint USDH by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back USDH is burned.",
    onCoinGecko: "true",
    gecko_id: "usdh",
    cmcId: "19550",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "birdeye",
    auditLinks: null,
    twitter: "https://twitter.com/hubbleprotocol",
    wiki: "https://wiki.defillama.com/wiki/Hubble_Protocol",
  },
  {
    id: "66",
    name: "Frax Price Index",
    address: "0x5ca135cb8527d76e932f34b5145575f9d8cbe08e",
    symbol: "FPI",
    url: "https://frax.finance/",
    description:
      "The Frax Price Index (FPI) is the second stablecoin of the Frax Finance ecosystem. FPI is a stablecoin pegged to a basket of real-world consumer items as defined by the US CPI-U average.",
    mintRedeemDescription:
      "Using the Frax Finance app, users swap FRAX to mint FPI at the current exchange rate. FPI can be redeemed for FRAX at any time.",
    onCoinGecko: "true",
    gecko_id: "frax-price-index",
    cmcId: null,
    pegType: "peggedVAR",
    pegMechanism: "algorithmic",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/fraxfinance",
    wiki: "https://wiki.defillama.com/wiki/Frax",
  },
  {
    id: "67",
    name: "Bean",
    address: "0xBEA0000029AD1c77D3d5D23Ba2D8893dB9d1Efab",
    symbol: "BEAN",
    url: "https://bean.money/",
    description:
      "Beanstalk is a permissionless fiat stablecoin protocol built on Ethereum.",
    mintRedeemDescription:
      "Beanstalk uses the liquidity and time weighted average shortage or excess of Beans in the BEAN:3CRV pool to dynamically increase the Bean supply or burn it and issue debt in order to maintain its peg.",
    onCoinGecko: "false",
    gecko_id: "bean2", // should be updated once it is added to CG
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/beanstalkfarms",
    wiki: "https://wiki.defillama.com/wiki/Beanstalk",
  },
  {
    id: "68",
    name: "USDLemma",
    address: "0xdb41ab644AbcA7f5ac579A5Cf2F41e606C2d6abc",
    symbol: "USDL",
    url: "https://www.lemma.finance/",
    description:
      "Lemma is a decentralized finance (DeFi) protocol with two products: a leveraged basis trading vault and USDL, a stablecoin that is fully decentralized, 100% capital efficient and USD pegged.",
    mintRedeemDescription:
      "Using the Lemma Finance app, users mint USDL by depositing an accepted asset into the protocol where it establishes a market neutral trading position on decentralized exchanges. When the loan is repaid to retrieve the collateral, the paid back USDL is burned.",
    onCoinGecko: "false",
    gecko_id: "usdlemma",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/LemmaFinance",
    wiki: "https://wiki.defillama.com/wiki/LemmaFinance",
  },
  {
    id: "69",
    name: "Pando USD",
    address: null,
    symbol: "PUSD",
    url: "https://pando.im/",
    description:
      "Pando USD is a stablecoin pegged to the US Dollar on the Mixin Network.",
    mintRedeemDescription:
      "Using the Pando Leaf app, users mint PUSD by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back PUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "pando-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/pando_im",
    wiki: "https://wiki.defillama.com/wiki/Pando",
    delisted: true,
  },
  {
    id: "70",
    name: "DigitalDollar",
    address: "arbitrum:0xf0b5ceefc89684889e5f7e0a7775bd100fcd3709",
    symbol: "DUSD",
    url: "https://fluid.ch/",
    description:
      "DUSD is a secure, transparent, democratic Digital Dollar on Arbitrum. All DUSD are 1:1 backed by real dollars.",
    mintRedeemDescription:
    "Fluid customers who have undergone a verification process can exchange USD for DUSD and redeem DUSD for USD.",
    onCoinGecko: "true",
    gecko_id: "digitaldollar",
    cmcId: "19933",
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "defillama",
    auditLinks: [
      "https://res.cloudinary.com/eoi-digital/image/upload/v1634004020/Audit_Report_-_Fluid_Finance_26.08.2021.pdf",
    ],
    twitter: "https://twitter.com/fluid_fi/",
    wiki: "https://wiki.defillama.com/wiki/Fluid_Finance",
  },
  {
    id: "71",
    name: "Vesta Stable",
    address: "arbitrum:0x64343594ab9b56e99087bfa6f2335db24c2d1f17",
    symbol: "VST",
    url: "https://vestafinance.xyz/",
    description:
      "Vesta is a layer 2-first lending protocol where users can deposit collateral to mint VST (Vesta Stable) - a USD-pegged stablecoin.",
    mintRedeemDescription:
    "Using the Vesta Finance app, users mint VST by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back VST is burned.",
    onCoinGecko: "true",
    gecko_id: "vesta-stable",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/vestafinance",
    wiki: "https://wiki.defillama.com/wiki/Vesta_Finance",
  },
  {
    id: "72",
    name: "Kolibri USD",
    address: "tezos:KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV",
    symbol: "KUSD",
    url: "https://kolibri.finance/",
    description:
      "Kolibri is an Tezos based stablecoin built on Collateralized Debt Positions (CDPs).",
    mintRedeemDescription:
    "Using the Kolibri app, users mint KUSD by depositing an accepted collateral asset into an oven. When the loan is repaid to retrieve the collateral, the paid back KUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "kolibri-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/HoverEng",
    wiki: "https://wiki.defillama.com/wiki/Kolibri",
  },
  {
    id: "73",
    name: "USDtez",
    address: "tezos:KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9",
    symbol: "USDTZ",
    url: "https://usdtz.com/",
    description:
      "USD Tez (USDtz) is the first USD stablecoin on Tezos. USDtz is reserve-backed 1-1 by FIAT, follows regulatory compliance standards, and publishes monthly audit reports. Unlike other stablecoins, USD Tez combines Tezos-exclusive domain expertise with the scalability of a full FIAT reserve",
    mintRedeemDescription:
      "Zero fee minting and redemption of USD Tez (USDtz) is available to users who are approved through a KYC enrollment process. Accepted collateral includes select US-regulated FIAT-backed stablecoins.",
    onCoinGecko: "true",
    gecko_id: "usdtez",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/usdtz",
    wiki: "https://wiki.defillama.com/wiki/USDtez",
  },
  {
    id: "74",
    name: "Moremoney USD",
    address: "avax:0x0f577433Bf59560Ef2a79c124E9Ff99fCa258948",
    symbol: "MONEY",
    url: "https://moremoney.finance/",
    description:
      "Moremoney is a lending protocol for opening (over)collateralized debt positions (CDP) using liquidity pool tokens, interest-bearing tokens (ibTKNs) and other major tokens as collateral.",
    mintRedeemDescription:
    "Using the Moremoney app, users mint MONEY by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back MONEY is burned.",
    onCoinGecko: "true",
    gecko_id: "moremoney-usd",
    cmcId: "18758",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/Moremoneyfi",
    wiki: "https://wiki.defillama.com/wiki/Moremoney_Finance",
  },
  {
    id: "75",
    name: "Youves uUSD",
    address: "tezos:KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW",
    symbol: "UUSD",
    url: "https://youves.com/",
    description:
      "uUSD is stablecoin pegged to USD on Tezos. It is fungible by design and backed by tez collateral.",
    mintRedeemDescription:
    "Using the youves app, users mint uUSD by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back uUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "youves-uusd",
    cmcId: "15041",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/youves_com",
    wiki: "https://wiki.defillama.com/wiki/Youves",
  },
  {
    id: "76",
    name: "Interest Protocol",
    address: "0x2a54ba2964c8cd459dc568853f79813a60761b58",
    symbol: "USDI",
    url: "https://interestprotocol.io/",
    description:
      "Interest Protocol (IP) is a fractional reserve banking protocol on the Ethereum blockchain that pays interest to all depositors. Interest Protocol issues a stablecoin, named USDi, that is both over-collateralized and highly scalable.",
    mintRedeemDescription:
    "Using the Interest Protocol app, users mint USDi by depositing an accepted collateral asset into a vault or swapping for USDC. When the loan is repaid to retrieve the collateral, the paid back USDi is burned.",
    onCoinGecko: "true",
    gecko_id: "interest-protocol",
    cmcId: "20598",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/InterestDeFi",
    wiki: "https://wiki.defillama.com/wiki/Interest_Protocol",
  },
  {
    id: "77",
    name: "LUGH",
    address: "tezos:KT1JBNFcB5tiycHNdYGYCtR3kk6JaJysUCi8",
    symbol: "EURL",
    url: "https://www.lugh.io/",
    description:
      "LUGH (EURL) is a euro-pegged stablecoin on Tezos and Ethereum.",
    mintRedeemDescription:
    "Corporates who have undergone a verification process can exchange EUR for EURL and redeem EURL for EUR.",
    onCoinGecko: "false",
    gecko_id: "lugh",
    cmcId: null,
    pegType: "peggedEUR",
    pegMechanism: "fiat-backed",
    priceSource: null,
    auditLinks: ["https://www.lugh.io/"],
    twitter: "https://twitter.com/LughStablecoin",
    wiki: "https://wiki.defillama.com/wiki/LUGH",
  },
  {
    id: "78",
    name: "Note",
    address: "canto:0x4e71a2e537b7f9d9413d3991d37958c0b5e1e503",
    symbol: "NOTE",
    url: "https://canto.io/",
    description:
      "NOTE is the unit of account on Canto. NOTE is an over-collateralized currency with a value perpetually rebalanced toward $1 through an algorithmic interest rate policy.",
    mintRedeemDescription:
    "NOTE is a fully immutable ERC-20 token backed by collateral lent to the Canto Lending Market. It can only be borrowed by users who post select collateral assets such as USDC, USDT, CANTO, ETH, ATOM, or Canto LP tokens.",
    onCoinGecko: "true",
    gecko_id: "note",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/CantoPublic",
    wiki: "https://wiki.defillama.com/wiki/Canto",
  },
  {
    id: "79",
    name: "HAY",
    address: "bsc:0x0782b6d8c4551b9760e74c0545a9bcd90bdc41e5",
    symbol: "HAY",
    url: "https://helio.money/",
    description:
      "HAY is a decentralized, unbiased, collateral-backed destablecoin soft-pegged to the US Dollar.",
    mintRedeemDescription:
    "Using the Helio app, users mint HAY by depositing BNB into a vault. When the loan is repaid to retrieve the collateral, the paid back HAY is burned.",
    onCoinGecko: "true",
    gecko_id: "helio-protocol-hay",
    cmcId: "21330",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "dexscreener",
    auditLinks: null,
    twitter: "https://twitter.com/Helio_Money",
    wiki: "https://wiki.defillama.com/wiki/Helio_Protocol",
  },
  /*
  {
    id: "80",
    name: "USD2",
    address: null,
    symbol: "USD2",
    url: "https://usd2.lago.finance/",
    description:
      "USD2 is a fully-redeemable, decentralized stablecoin on the Kadena blockchain. It is currently 1:1 backed by collateral, in the form of USDC.",
    mintRedeemDescription:
    "Using the Lago Finance app, users swap kwUSDC to mint USD2 1:1. USD2 can be redeemed for kwUSDC 1:1 at any time.",
    onCoinGecko: "false",
    gecko_id: "usd2",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed", // currently is crypto-backed for v1, but will change to FRAX mechanism for v2
    priceSource: "kaddex",
    auditLinks: null,
    twitter: "https://twitter.com/lagofinance",
    wiki: "https://wiki.defillama.com/wiki/Lago_Finance",
  },
  */
  {
    id: "81",
    name: "USK",
    address: null,
    symbol: "USK",
    url: "https://kujira.app/",
    description:
      "USK is an over-collateralized Cosmos stablecoin soft-pegged to the USD and initially backed by ATOM.",
    mintRedeemDescription:
    "Using the Kujira BLUE app, users mint USK by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back USK is burned.",
    onCoinGecko: "true",
    gecko_id: "usk",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/TeamKujira",
    wiki: "https://wiki.defillama.com/wiki/Kujira",
  },
  {
    id: "82",
    name: "arUSD",
    address: "avax:0x025AB35fF6AbccA56d57475249baaEae08419039",
    symbol: "ARUSD",
    url: "https://arable.finance/",
    description:
      "Arable offers farms for staking with synthetic LP and synthetic cryptocurrencies. arUSD is a token that is pegged to USD. You can swap arUSD for any other synths on the Arable platform.",
    mintRedeemDescription:
    "Using the Arable Finance app, users mint arUSD by depositing an accepted collateral asset into a vault. When the loan is repaid to retrieve the collateral, the paid back arUSD is burned.",
    onCoinGecko: "false",
    gecko_id: "arable-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/ArableProtocol",
    wiki: "https://wiki.defillama.com/wiki/Arable_Protocol",
  },
  {
    id: "83",
    name: "USDW",
    address: "ethpow:0x520A36eE3aa0b506288915f91Fb4BBB23d09a7D7",
    symbol: "USDW",
    url: "https://www.realprotocol.xyz/",
    description:
      "Real is a decentralized borrowing protocol on the EthereumPoW network that allows you to draw interest-free loans against Ether used as collateral. Loans are paid out in USDW (a USD pegged stablecoin) and need to maintain a minimum collateral ratio of 115%.",
    mintRedeemDescription:
    "Using the Real Protocol app, users mint USDW by depositing Ether into a vault. When the loan is repaid to retrieve the collateral, the paid back USDW is burned.",
    onCoinGecko: "false",
    gecko_id: "usdw",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/realprotocoleth",
    wiki: "https://wiki.defillama.com/wiki/Real_Protocol",
  },
  {
    id: "84",
    name: "BOB",
    address: "polygon:0xb0b195aefa3650a6908f15cdac7d92f8a5791b0b",
    symbol: "BOB",
    url: "https://www.zkbob.com/",
    description:
      "BOB is a multi-chain stable token (stablecoin) enhanced with optional privacy features. Once BOB is deposited in the zkBob app, pool participants can transfer any amount of BOB amongst themselves in a private, secure manner.",
    mintRedeemDescription:
    "BOB minting is handled with a multi-sig Safe by a distributed reserve board.",
    onCoinGecko: "true",
    gecko_id: "bob",
    cmcId: "21882",
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "dexscreener",
    auditLinks: null,
    twitter: "https://twitter.com/zkBob_",
    wiki: "https://wiki.defillama.com/wiki/zkBob",
  },
  {
    id: "85",
    name: "Real USD",
    address: "polygon:0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63",
    symbol: "USDR",
    url: "https://www.tangible.store/realusd",
    description:
      "Real USD (USDR v2) is a natively rebasing, yield-bearing, overcollateralized stablecoin, pegged to the US dollar. Collateralizing USDR will be yield-generating, tokenized real estate that is inflation-resistant and wealth generating.",
    mintRedeemDescription:
    "Using Tangible, users can swap DAI to mint USDR 1:1. A portion of that DAI is then converted into tokenized real estate through Tangible's existing marketplace. Users receive a daily rebase. USDR can be redeemed for DAI 1:1 at any time.",
    onCoinGecko: "true",
    gecko_id: "real-usd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/tangibleDAO",
    wiki: "https://wiki.defillama.com/wiki/Tangible",
  },
  {
    id: "86",
    name: "Zunami USD",
    address: "0x015b94ab2b0a14a96030573fbcd0f3d3d763541f",
    symbol: "UZD",
    url: "https://www.zunami.io/",
    description:
      "UZD is a dollar-pegged stablecoin with wrapped stable assets (from Curve and Convex through Zunami Protocol) as collateral.",
    mintRedeemDescription:
    "Using the Zunami Protocol app, users can LP in a 3-pool and then deposit the LP tokens to mint UZD. UZD can be redeemed for LP tokens at any time.",
    onCoinGecko: "true",
    gecko_id: "zunami-protocol",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "curve",
    auditLinks: null,
    twitter: "https://twitter.com/ZunamiProtocol",
    wiki: "https://wiki.defillama.com/wiki/Zunami_Protocol",
  },
  {
    id: "87",
    name: "USDi",
    address: "0x83131242843257bc6C43771762ba467346Efb2CF",
    symbol: "USDI",
    url: "https://bankofchain.io/",
    description:
      "USDi is the USD-pegged stablecoin of Bank of Chain ('BoC'), a decentralized yield generation protocol.",
    mintRedeemDescription:
    "Using the Bank of Chain app, users can deposit the three major stablecoins (USDT, USDC, DAI) in any desired combination and amount to mint USDi. USDi can be redeemed for its underlying stablecoins 1:1 at any time.",
    onCoinGecko: "false",
    gecko_id: "bank-of-chain",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/bankofchain_dao",
    wiki: "https://wiki.defillama.com/wiki/BankOfChain",
  },
  {
    id: "88",
    name: "iUSD",
    address: null,
    symbol: "IUSD",
    url: "https://indigoprotocol.io/",
    description:
      "iUSD is a synthetic CDP stablecoin native to Cardano.",
    mintRedeemDescription:
    "Using the Indigo app, users can mint iUSD by depositing ADA as collateral into a CDP. When the loan is repaid to retrieve the collateral, the paid back iUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "iusd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/Indigo_protocol",
    wiki: "https://wiki.defillama.com/wiki/Indigo_Protocol",
  },
  {
    id: "89",
    name: "XAI",
    address: "0xd7C9F0e536dC865Ae858b0C0453Fe76D13c3bEAc",
    symbol: "XAI",
    url: "https://www.silo.finance/",
    description:
      "XAI is an over-collateralized stablecoin with a soft peg to the US Dollar in the Silo lending protocol.",
    mintRedeemDescription:
    "Using the Silo Finance app, users can borrow XAI by depositing ETH or USDC as collateral. When the loan is repaid to retrieve the collateral, the paid back XAI is burned.",
    onCoinGecko: "true",
    gecko_id: "xai",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "uniswap",
    auditLinks: null,
    twitter: "https://twitter.com/SiloFinance",
    wiki: "https://wiki.defillama.com/wiki/Silo_Finance",
  },
  {
    id: "90",
    name: "Redeemable USD",
    address: null,
    symbol: "RUSD",
    url: "https://www.shareslake.com/",
    description:
      "Redeemable USD is a fiat-backed stablecoin on both the Cardano and Shareslake networks. It is a USD backed stablecoin in a 1:1 basis.",
    mintRedeemDescription:
    "Using the Shareslake Dashboard, users can deposit USD on Shareslake or ADA on Cardano to mint RUSD. RUSD can be redeemed for USD at any time.",
    onCoinGecko: "false",
    gecko_id: "redeemable",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "fiat-backed",
    priceSource: null,
    auditLinks: null,
    twitter: "https://twitter.com/shareslake",
    wiki: "https://wiki.defillama.com/wiki/Shareslake",
  },
  {
    id: "91",
    name: "Iron Bank EURO",
    address: "0x96e61422b6a9ba0e068b6c5add4ffabc6a4aae27",
    symbol: "IBEUR",
    url: "https://www.ib.xyz",
    description:
      "ibXX (Fixed Forex assets, example; ibCHF, ibEUR, ibAUD) are erc20 tokens that are pegged to their corresponding forex pair name. They can only be borrowed via Iron Bank by supplying collateral in one of Iron Bank's accepted collateral options.",
    mintRedeemDescription:
      "Users can borrow ibEUR from the Iron Bank App (https://www.ib.xyz) or the Fixed Forex app (https://fixedforex.fi/) by supplying an accepted collateral.",
    onCoinGecko: "true",
    gecko_id: "iron-bank-euro",
    cmcId: null,
    pegType: "peggedEUR",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/ibdotxyz",
    wiki: "https://wiki.defillama.com/wiki/Iron_Bank",
  },
  {
    id: "92",
    name: "Meme Dollar",
    address: "0x02814f435dd04e254be7ae69f61fca19881a780d",
    symbol: "PINA",
    url: "https://www.dontdiememe.com/pina",
    description:
      "Pina is also a stable dollar pegged to the value of $1. Using mechanisms inspired by Dynamic Set Dollar (DSD), they have optimized $Pina to better serve the needs of their marketplace.",
    mintRedeemDescription:
    "If the price of PINA is less than 1$, the supply is changed by emitting coupons to reduce the supply. You can stake PINA or LP PINA-USDC in order to get more PINA.",
    onCoinGecko: "true",
    gecko_id: "meme-dollar",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "algorithmic",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/DontDieMeme",
    wiki: "https://wiki.defillama.com/wiki/DontDieMeme",
  },
  {
    id: "93",
    name: "Djed StableCoin",
    address: "cardano:8db269c3ec630e06ae29f74bc39edd1f87c819f1056206e879a1cd61446a65644d6963726f555344",
    symbol: "DJED",
    url: "https://djed.xyz/",
    description:
    "Cardano's native overcollateralized stablecoin, developed by IOG and powered by COTI. DJED is backed by ADA and uses SHEN as a reserve coin",
    mintRedeemDescription:
    "Using the DJED App (https://djed.xyz/) users supply ADA as collateral to receive DJED. It uses a collateral ratio between 400% and 800% for DJED and SHEN",
    onCoinGecko: "false",
    gecko_id: "djed",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/DjedStablecoin",
    wiki: null,
  },
  {
    id: "94",
    name: "BaoUSD",
    address: "0x7945b0a6674b175695e5d1d08ae1e6f13744abb0",
    symbol: "BAOUSD",
    url: "https://app.bao.finance",
    description:
    "BaoUSD is a CDP stablecoin, its over-collateralized and issued through our Bao Market",
    mintRedeemDescription:
    "Using the Bao Finance app, users can borrow BAOUSD by depositing ETH, USDC or bSTBL as collateral. When the loan is repaid to retrieve the collateral, the paid back BAOUSD is burned.",
    onCoinGecko: "true",
    gecko_id: "baousd",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: null,
    twitter: "https://twitter.com/BaoCommunity",
    wiki: null,
  },
  {
    id: "95",
    name: "Composite",
    address: null,
    symbol: "CMST",
    url: "https://harborprotocol.one/home",
    description:
      "CMST is an over-collateralized stablecoin for the Cosmos.",
    mintRedeemDescription:
    "Users can deposit safelisted Interchain assets on Harbor protocol as collateral and mint new $CMST.",
    onCoinGecko: "true",
    gecko_id: "composite",
    cmcId: null,
    pegType: "peggedUSD",
    pegMechanism: "crypto-backed",
    priceSource: "coingecko",
    auditLinks: "https://github.com/oak-security/audit-reports/tree/master/Comdex",
    twitter: "https://twitter.com/Composite_Money",
    wiki: null,
  },
  {
  id: "96",
  name: "Coin98 Dollar",
  address: null,
  symbol: "CUSD",
  url: "https://coin98.com/dollar",
  description:
    "CUSD is a decentralized stablecoin that is fully collateralized by assets in reserve",
  mintRedeemDescription:
  "In order to convert to 1 CUSD, a total of $1 worth of the collateralized assets must be sent into the CUSD Reserve smart contract. Specifically, in the initial phase, the collateral ratio to convert to 1 CUSD will be $1 worth of fiat-backed stablecoins - BUSD (on BNB Chain) and USDC (on Solana and Ethereum)",
  onCoinGecko: "true",
  gecko_id: "coin98-dollar",
  cmcId: "21871",
  pegType: "peggedUSD",
  pegMechanism: "crypto-backed",
  priceSource: "coingecko",
  auditLinks: null,
  twitter: "https://twitter.com/coin98_wallet",
  wiki: null,
},
{
  id: "97",
  name: "USP Stablecoin",
  address: "avax:0xdaCDe03d7Ab4D81fEDdc3a20fAA89aBAc9072CE2",
  symbol: "USP",
  url: "https://app.platypus.finance/usp",
  description:
    "An over-collateralized ERC-20 stablecoin built on the Platypus stableswap",
  mintRedeemDescription:
  "Users can deposits collateral into the Platypus Main Pool and stake their LP tokens into the MasterPlatypus to farm PTP. At the same time, it is possible for users to mint USP based on the the collateral factor",
  onCoinGecko: "false",
  gecko_id: "usp-stable",
  cmcId: null,
  pegType: "peggedUSD",
  pegMechanism: "crypto-backed",
  priceSource: null,
  auditLinks: null,
  twitter: "https://twitter.com/Platypusdefi",
  wiki: null,
},
{
  id: "98",
  name: "EUROe Stablecoin",
  address: "0x820802Fa8a99901F52e39acD21177b0BE6EE2974",
  symbol: "EUROe",
  url: "https://www.euroe.com/",
  description:
    "EUROe is a euro stablecoin currently available on Ethereum. EUROe is fully fiat-backed and regulated as an e-money institution in Europe by the Finnish Financial Supervisory Authority",
  mintRedeemDescription:
  "EUROe customers who have undergone a verification process can exchange USD for GUSD and redeem GUSD for USD.",
  onCoinGecko: "true",
  gecko_id: "euroe-stablecoin",
  cmcId: null,
  pegType: "peggedEUR",
  pegMechanism: "fiat-backed",
  priceSource: "coingecko",
  auditLinks: ["https://dev.euroe.com/docs/Stablecoin/audits"],
  twitter: "https://twitter.com/EUROemoney",
  wiki: null,
},
] as PeggedAsset[];
