import type { PeggedAsset } from "./types";

export type { PeggedAsset };

export const peggedCategoryList = ["stablecoins"]; // this should include all strings from union type PeggedCategory

/*
`chain` is the first chain of a protocol we tracked at defillama,
  so if a protocol launches on Ethereum and we start tracking it there, and then it launches on polygon and
  we start tracking it on both polygon and ethereum, then `chain` should be set to `Ethereum`.

`chains` is not used by the current code, but good to fill it out because it is used in our test to detect errors
*/

export default [
  {
    id: "1",
    name: "Tether",
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    symbol: "USDT",
    url: "https://tether.to/",
    description:
      "Tether tokens offer the stability and simplicity of fiat currencies coupled with the innovative nature of blockchain technology, representing a perfect combination of both worlds.",
    chain: "Ethereum",
    gecko_id: "tether",
    cmcId: "825",
    category: "stablecoins", // is for the frontend
    pegType: "peggedUSD", // should match balance key returned by adapter
    priceSource: "chainlink",
    chains: [
      "Ethereum",
      "Polygon",
      "BSC",
      "Avalanche",
      "Solana",
      "Arbitrum",
      "Optimism",
      "Boba",
      "Metis",
      "Moonbeam",
      "KCC",
      "Moonriver",
      "Harmony",
      "Syscoin",
      "Heco",
      "OKExChain",
      "IoTeX",
      "Omni",
      "Aurora",
      "Algorand",
      "Milkomeda",
      "Kardia",
      "Telos",
      "Fuse",
      "TomoChain",
      "Meter",
      "Tron",
      "Liquidchain",
      "Bittorrent",
      "Crab",
      "EOS",
      "Statemine",
      "Evmos",
      "Oasis",
      "Terra",
      "Astar",
      "Gnosis",
      "Theta",
      "RSK",
      "REINetwork",
      "Loopring",
      "zkSync",
      "Shiden",
      "Fantom",
    ],
    twitter: "https://twitter.com/Tether_to",
  },
  {
    id: "2",
    name: "USD Coin",
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    symbol: "USDC",
    url: "https://www.circle.com/usdc/",
    description: "Digital dollars for global business.",
    chain: "Ethereum",
    gecko_id: "usd-coin",
    cmcId: "3408",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: [
      "Ethereum",
      "Polygon",
      "BSC",
      "Solana",
      "Avalanche",
      "Arbitrum",
      "Optimism",
      "Boba",
      "Metis",
      "KCC",
      "Moonriver",
      "Harmony",
      "OKExChain",
      "Moonbeam",
      "Syscoin",
      "TomoChain",
      "Ronin",
      "Aurora",
      "Fuse",
      "Meter",
      "Telos",
      "Milkomeda",
      "Elastos",
      "Algorand",
      "Tron",
      "Terra",
      "Oasis",
      "Crab",
      "Evmos",
      "Astar",
      "Hedera",
      "Stellar",
      "Flow",
      "Gnosis",
      "Theta",
      "RSK",
      "REINetwork",
      "Loopring",
      "zkSync",
      "Shiden",
      "Fantom",
      "DFK",
    ],
    twitter: "",
  },
  {
    id: "3",
    name: "TerraUSD",
    address: "",
    symbol: "UST",
    url: "https://www.terra.money/",
    description: "Programmable money for the internet.",
    chain: "Terra",
    gecko_id: "terrausd",
    cmcId: "7129",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: [
      "Terra",
      "Ethereum",
      "Polygon",
      "BSC",
      "Solana",
      "Harmony",
      "Fantom",
      "Aurora",
      "Avalanche",
      "Osmosis",
      "Moonbeam",
      "Oasis",
      "Celo",
      "Fuse",
      "Arbitrum",
      "Optimism",
      "Metis",
      "DFK",
    ],
    twitter: "https://twitter.com/terra_money",
  },
  {
    id: "4",
    name: "Binance USD",
    address: "0x4fabb145d64652a948d72533023f6e7a623c7c53",
    symbol: "BUSD",
    url: "https://www.binance.com/en/busd",
    description:
      "BUSD is a 1:1 USD-backed stablecoin approved by the New York State Department of Financial Services (NYDFS), issued in partnership with Paxos.",
    chain: "Ethereum",
    gecko_id: "binance-usd",
    cmcId: "4687",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: [
      "Ethereum",
      "BSC",
      "Avalanche",
      "Harmony",
      "IoTeX",
      "OKExChain",
      "Moonriver",
      "Solana",
      "Polygon",
      "Fuse",
      "Meter",
      "Moonbeam",
      "Milkomeda",
      "Elastos",
      "Aurora",
      "Oasis",
      "Terra",
      "Shiden",
      "Astar",
      "Evmos",
      "Syscoin",
      "Boba",
      "Metis",
      "Fantom",
      "KCC",
      "RSK",
      "Theta",
    ],
    twitter: "https://twitter.com/PaxosGlobal",
  },
  {
    id: "5",
    name: "Dai",
    address: "0x6b175474e89094c44da98b954eedeac495271d0f",
    symbol: "DAI",
    url: "https://makerdao.com/",
    description:
      "Dai is a stable, decentralized currency that does not discriminate. Any individual or business can realize the advantages of digital money.",
    chain: "Ethereum",
    gecko_id: "dai",
    cmcId: "4943",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: [
      "Ethereum",
      "Solana",
      "Polygon",
      "BSC",
      "Optimism",
      "Harmony",
      "Avalanche",
      "Arbitrum",
      "Moonriver",
      "Aurora",
      "Fantom",
      "Moonbeam",
      "Syscoin",
      "Milkomeda",
      "Astar",
      "Oasis",
      "Evmos",
      "Gnosis",
      "Terra",
      "RSK",
      "REINetwork",
      "Loopring",
      "zkSync",
      "Aztec",
      "Velas",
      "Shiden",
      "Boba",
    ],
    twitter: "https://twitter.com/MakerDAO",
  },
  {
    id: "6",
    name: "Frax",
    address: "0x853d955acef822db058eb8505911ed77f175b99e",
    symbol: "FRAX",
    url: "https://frax.finance/",
    description: "Frax is the world’s first fractional-algorithmic stablecoin.",
    chain: "Ethereum",
    gecko_id: "frax",
    cmcId: "6952",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: [
      "Ethereum",
      "BSC",
      "Avalanche",
      "Arbitrum",
      "Aurora",
      "Boba",
      "Fantom",
      "Evmos",
      "Harmony",
      "Moonbeam",
      "Moonriver",
      "Optimism",
      "Polygon",
      "Solana",
      "zkSync",
      "Milkomeda",
    ],
    twitter: "https://twitter.com/fraxfinance",
  },
  {
    id: "7",
    name: "TrueUSD",
    address: "0x0000000000085d4780b73119b644ae5ecd22b376",
    symbol: "TUSD",
    url: "https://trueusd.com/",
    description:
      "The first regulated stablecoin fully backed by the US Dollar.",
    chain: "Ethereum",
    gecko_id: "true-usd",
    cmcId: "2563",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: [
      "Ethereum",
      "BSC",
      "Avalanche",
      "Polygon",
      "Arbitrum",
      "Fantom",
      "Tron",
      "Syscoin",
      "Heco",
      "Cronos",
    ],
    twitter: "https://twitter.com/tusdio",
  },
  {
    id: "8",
    name: "Liquity USD",
    address: "0x5f98805a4e8be255a32880fdec7f6728c6568ba0",
    symbol: "LUSD",
    url: "https://www.liquity.org/",
    description:
      "LUSD is an algorithmic, immutable, governance-free USD-pegged stablecoin used to pay out loans on the Liquity protocol. LUSD can be redeemed against the underlying Ether collateral at face value.",
    chain: "Ethereum",
    gecko_id: "liquity-usd",
    cmcId: "9566",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: ["Ethereum", "Polygon", "Optimism"],
    twitter: "https://twitter.com/LiquityProtocol",
  },
  {
    id: "9",
    name: "Fei USD",
    address: "0x956f47f50a910163d8bf957cf5846d573e7f87ca",
    symbol: "FEI",
    url: "https://fei.money/",
    description:
      "Fei is a decentralized, scalable, and DeFi-native stablecoin protocol.",
    chain: "Ethereum",
    gecko_id: "fei-usd",
    cmcId: "8642",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: ["Ethereum"],
    twitter: "https://twitter.com/feiprotocol",
  },
  {
    id: "10",
    name: "Magic Internet Money",
    address: "0x956f47f50a910163d8bf957cf5846d573e7f87ca",
    symbol: "MIM",
    url: "https://abracadabra.money/",
    description:
      "Abracadabra.money is a spell book that allows users to produce magic internet money.",
    chain: "Ethereum",
    gecko_id: "magic-internet-money",
    cmcId: "162",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: [
      "Ethereum",
      "Polygon",
      "Avalanche",
      "Arbitrum",
      "Fantom",
      "BSC",
      "Moonriver",
      "Boba",
      "Metis",
    ],
    twitter: "https://twitter.com/MIM_Spell",
  },
  {
    id: "11",
    name: "Pax Dollar",
    address: "0x8e870d67f660d95d5be530380d0ec0bd388289e1",
    symbol: "USDP",
    url: "https://paxos.com/usdp/",
    description:
      "USDP gives customers the ability to store and send US Dollars with freedom, unrestricted by the limits of traditional banking.",
    chain: "Ethereum",
    gecko_id: "paxos-standard",
    cmcId: "3330",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: ["Ethereum", "BSC"],
    twitter: "https://twitter.com/paxosglobal",
  },
  {
    id: "12",
    name: "Neutrino USD",
    address: "0x674c6ad92fd080e4004b2312b45f796a192d27a0",
    symbol: "USDN",
    url: "https://neutrino.at/",
    description:
      "Neutrino USD (USDN) is an algorithmic stablecoin pegged to the US dollar and backed by WAVES.",
    chain: "Waves",
    gecko_id: "neutrino",
    cmcId: "5068",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: ["Waves", "Ethereum", "Polygon", "BSC"],
    twitter: "https://twitter.com/neutrino_proto",
  },
  {
    id: "13",
    name: "YUSD Stablecoin",
    address: "0x111111111111ed1d73f860f57b2798b683f2d325",
    symbol: "YUSD",
    url: "https://yeti.finance/",
    description:
      "Yeti Finance is a cross-margin lending protocol on Avalanche that allows users to borrow up to 21x against their portfolio and receive YUSD, an overcollateralized stablecoin.",
    chain: "Avalanche",
    gecko_id: "yusd-stablecoin",
    cmcId: "19577",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: null,
    chains: ["Avalanche"],
    twitter: "https://twitter.com/YetiFinance",
  },
  {
    id: "14",
    name: "USDD",
    address: "TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn",
    symbol: "USDD",
    url: "https://usdd.io/",
    description:
      "USDD is a cryptocurrency issued by the TRON DAO Reserve with a stable price and diverse use cases.",
    chain: "Tron",
    gecko_id: "usdd",
    cmcId: "19891",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "uniswap",
    chains: ["Tron", "Bittorrent", "Ethereum", "BSC"],
    twitter: "https://twitter.com/usddio",
  },
  {
    id: "15",
    name: "Dola",
    address: "0x865377367054516e17014ccded1e7d814edc9ce4",
    symbol: "DOLA",
    url: "https://www.inverse.finance/",
    description:
      "DOLA is a stablecoin pegged to the US Dollar.  It can also be used as collateral within the Frontier protocol to achieve high capital efficiency, leverage and native yield.",
    chain: "Ethereum",
    gecko_id: "dola-usd",
    cmcId: "19191",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "uniswap",
    chains: ["Ethereum", "Fantom"],
    twitter: "https://twitter.com/InverseFinance",
  },
  {
    id: "16",
    name: "Parrot USD",
    address: "Ea5SjE2Y6yvCeW5dYTn7PYMuW5ikXkvbGdcmSnXeaLjS",
    symbol: "PAI",
    url: "https://parrot.fi/",
    description:
      "The Parrot Protocol is a DeFi network built on Solana that will include the stablecoin PAI, a non-custodial lending market, and a margin trading vAMM.",
    chain: "Solana",
    gecko_id: "parrot-usd",
    cmcId: null,
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: null,
    chains: ["Solana"],
    twitter: "https://twitter.com/gopartyparrot",
  },
  {
    id: "17",
    name: "HUSD",
    address: "0xdf574c24545e5ffecb9a659c229253d4111d87e1",
    symbol: "HUSD",
    url: "https://www.stcoins.com/",
    description:
      "Combining the stability of the U.S. dollar with the efficiency of blockchain technology, HUSD is designed to be secure, liquid and convenient.",
    chain: "Ethereum",
    gecko_id: "husd",
    cmcId: "4779",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: null,
    chains: ["Ethereum", "Tron", "Heco", "Elastos", "Solana"],
    twitter: "https://twitter.com/Stablecoin_HUSD",
  },
  {
    id: "18",
    name: "Nexus USD",
    address: "0x1b84765de8b7566e4ceaf4d0fd3c5af52d3dde4f",
    symbol: "NUSD",
    url: "https://synapseprotocol.com/",
    description:
      'nUSD, or "nexus" USD, is a cross-chain stablecoin fully backed by the nexus stablecoin liquidity pool on Ethereum consisting of DAI, USDC, and USDT.',
    chain: "Ethereum",
    gecko_id: null,
    cmcId: null,
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: null,
    chains: [
      "Ethereum",
      "BSC",
      "Polygon",
      "Avalanche",
      "Arbitrum",
      "Fantom",
      "Harmony",
      "Boba",
      "Optimism",
      "Cronos",
      "Metis",
      "DFK",
    ],
    twitter: "https://twitter.com/SynapseProtocol",
  },
  {
    id: "19",
    name: "Gemini Dollar",
    address: "0x056fd409e1d7a124bd7017459dfea2f387b6d5cd",
    symbol: "GUSD",
    url: "https://www.gemini.com/dollar",
    description:
      "GUSD is a 1:1 USD-backed stablecoin issued by Gemini. Gemini customers can redeem a GUSD for $1 at Gemini.",
    chain: "Ethereum",
    gecko_id: "gemini-dollar",
    cmcId: "3306",
    category: "stablecoins",
    pegType: "peggedUSD",
    priceSource: "chainlink",
    chains: ["Ethereum", "Wanchain"],
    twitter: "https://twitter.com/gemini",
  },
] as PeggedAsset[];
