// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Global Dollar (global-dollar)   Match: address=0xe343167631d89b6ffc58b88d6b7fb0228795491d   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset global-dollar

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "hyperliquid", address: "0x9522133c663ba8c2a8a7b4f63dd2ac8dccce1505", decimals: 6 }, // ERC20 USDG0 (lz:hyperliquid)
    { chain: "xlayer", address: "0x4ae46a509f6b1d9056937ba4500cb143933d2dc8", decimals: 6 }, // ERC20 USDG (lz:xlayer)
  ],
};

export default layerzeroConfig;
