// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts
// Asset: Dai (dai)   Source (pinned via hyperlaneConfig.sourceChain): arbitrum
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts --asset dai
// Registry: @hyperlane-xyz/registry@25.0.0

import type { HyperlaneConfig } from "../helper/bridgeConfig";

const hyperlaneConfig: HyperlaneConfig = {
  sourceChain: "arbitrum",
  tokens: [
    { chain: "linea", address: "0xdF17853b7a56499d7d6CAe0cEa3003EfC8257B5b", decimals: 18 }, // EvmHypSynthetic DAI
  ],
};

export default hyperlaneConfig;
