// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Dai (dai)   Match: address=0x6b175474e89094c44da98b954eedeac495271d0f   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset dai

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "arbitrum", address: "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1", decimals: 18 }, // ERC20 DAI (lz:arbitrum)
    { chain: "bsc", address: "0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3", decimals: 18 }, // ERC20 DAI (lz:bsc)
    { chain: "fantom", address: "0x91a40c733c97a6e1bf876eaf9ed8c08102eb491f", decimals: 18 }, // NativeOFT DAI (lz:fantom)
    { chain: "glue", address: "0x6d74266681ba4db5d1c9d2adf4ffdcce21c90ed6", decimals: 18 }, // NativeOFT DAI (lz:glue)
    { chain: "harmony", address: "0x1d374ed0700a0ad3cd4945d66a5b1e08e5db20a8", decimals: 18 }, // ERC20 DAI (lz:harmony)
    { chain: "harmony", address: "0x7c07d01c9dab5abb09ce2b42242a7570f25fc2cc", decimals: 18 }, // ERC20 DAI (lz:harmony)
    { chain: "harmony", address: "0xd068722e4e1387e4958300d1e625d2878f784125", decimals: 18 }, // ERC20 DAI (lz:harmony)
  ],
};

export default layerzeroConfig;
