// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts
// Asset: Dai (dai)
// Sources detected: ethereum
// Registry: @wormhole-foundation/sdk-base@4.20.0
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts --asset dai

import type { WormholeConfig } from "../helper/bridgeConfig";

const wormholeConfig: WormholeConfig = [
  {
    sourceChain: "ethereum",
    tokens: [
      { chain: "arbitrum", address: "0x5c4f2FEFB97F7DF09E762d95C83f0Ccf8bCe8234", decimals: 18 }, // DAI
      { chain: "avax", address: "0xca319f81D147559e19A522A0a0310Dd43A96cA0F", decimals: 18 }, // DAI
      { chain: "base", address: "0x617Edadb51BfB43A44Bb91C7402129C23bA52381", decimals: 18 }, // DAI
      { chain: "bsc", address: "0x3413a030EF81a3dD5a302F4B4D11d911e12ed337", decimals: 18 }, // DAI
      { chain: "celo", address: "0x97926a82930bb7B33178E3c2f4ED1BFDc91A9FBF", decimals: 18 }, // DAI
      { chain: "moonbeam", address: "0x06e605775296e851FF43b4dAa541Bb0984E9D6fD", decimals: 18 }, // DAI
      { chain: "optimism", address: "0x098EA47D630b46df1E08e389e5e4466119c7dd30", decimals: 18 }, // DAI
      { chain: "polygon", address: "0x732EB1747ecCFC431fF19bc359ffc83755B1918c", decimals: 18 }, // DAI
    ],
  },
];

export default wormholeConfig;
