// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Ondo US Dollar Yield (ondo-us-dollar-yield)   Match: address=0x96f6ef951840721adbf46ac996b59e0235cb985c   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset ondo-us-dollar-yield

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "arbitrum", address: "0x35e050d3c0ec2d29d269a8ecea763a183bdf9a9d", decimals: 18 }, // ERC20 USDY (lz:arbitrum)
    { chain: "glue", address: "0x60db286bd4db7c60edbdca549faa4e9aa5e6d5a6", decimals: 18 }, // NativeOFT USDY (lz:glue)
    { chain: "mantle", address: "0x5be26527e817998a7206475496fde1e68957c5a6", decimals: 18 }, // ERC20 USDY (lz:mantle)
    { chain: "sei", address: "0x54cd901491aef397084453f4372b93c33260e2a6", decimals: 18 }, // ERC20 USDY (lz:sei)
  ],
};

export default layerzeroConfig;
