// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Reservoir Stablecoin (reservoir-rusd)   Match: address=0x09d4214c03d01f49544c0448dbe3a27f768f2b34   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset reservoir-rusd

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "arbitrum", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:arbitrum)
    { chain: "avax", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:avalanche)
    { chain: "base", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:base)
    { chain: "berachain", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:bera)
    { chain: "bsc", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:bsc)
    { chain: "hyperliquid", address: "0x866d66f64fb81461903e1e38d998e747ecf35e78", decimals: 18 }, // NativeOFT rUSD (lz:hyperliquid)
    { chain: "katana", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:katana)
    { chain: "linea", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:linea)
    { chain: "megaeth", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:megaeth)
    { chain: "monad", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:monad)
    { chain: "plasma", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:plasma)
    { chain: "plume_mainnet", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:plumephoenix)
    { chain: "sei", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:sei)
    { chain: "sonic", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:sonic)
    { chain: "unichain", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:unichain)
    { chain: "wc", address: "0x09d4214c03d01f49544c0448dbe3a27f768f2b34", decimals: 18 }, // NativeOFT rUSD (lz:worldchain)
  ],
};

export default layerzeroConfig;
