// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: PayPal USD (paypal-usd)   Match: address=0x6c3ea9036406852006290770bedfcaba0e23a0e8   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset paypal-usd

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "abstract", address: "0x142cdc44890978b506e745bb3bd11607b7f7faef", decimals: 6 }, // ERC20 PYUSD0 (lz:abstract)
    { chain: "arbitrum", address: "0x46850ad61c2b7d64d08c9c754f45254596696984", decimals: 6 }, // ERC20 PYUSD (lz:arbitrum)
    { chain: "avax", address: "0x142cdc44890978b506e745bb3bd11607b7f7faef", decimals: 6 }, // ERC20 PYUSD0 (lz:avalanche)
    { chain: "berachain", address: "0x688e72142674041f8f6af4c808a4045ca1d6ac82", decimals: 6 }, // NativeOFT BYUSD (lz:bera)
    { chain: "codex", address: "0x99af3eea856556646c98c8b9b2548fe815240750", decimals: 6 }, // ERC20 PYUSD0 (lz:codex)
    { chain: "flow", address: "0x2aabea2058b5ac2d339b163c6ab6f2b6d53aabed", decimals: 6 }, // NativeOFT PYUSD (lz:flow)
    { chain: "flow", address: "0x99af3eea856556646c98c8b9b2548fe815240750", decimals: 6 }, // ERC20 PYUSD0 (lz:flow)
    { chain: "fraxtal", address: "0x99af3eea856556646c98c8b9b2548fe815240750", decimals: 6 }, // ERC20 PYUSD0 (lz:fraxtal)
    { chain: "glue", address: "0x1c7c36b193224d0f72454f2a178e3b98aaefe8a5", decimals: 6 }, // NativeOFT PYUSD (lz:glue)
    { chain: "ink", address: "0x142cdc44890978b506e745bb3bd11607b7f7faef", decimals: 6 }, // ERC20 PYUSD0 (lz:ink)
    { chain: "plume_mainnet", address: "0x142cdc44890978b506e745bb3bd11607b7f7faef", decimals: 6 }, // ERC20 PYUSD0 (lz:plumephoenix)
    { chain: "plume_mainnet", address: "0xe9e8330a71912f03e54e7d93795acd9a56f070aa", decimals: 6 }, // NativeOFT PYUSD (lz:plumephoenix)
    { chain: "polygon", address: "0x99af3eea856556646c98c8b9b2548fe815240750", decimals: 6 }, // ERC20 PYUSD0 (lz:polygon)
    { chain: "sei", address: "0x142cdc44890978b506e745bb3bd11607b7f7faef", decimals: 6 }, // ERC20 PYUSD0 (lz:sei)
    { chain: "stable", address: "0x99af3eea856556646c98c8b9b2548fe815240750", decimals: 6 }, // ERC20 PYUSD0 (lz:stable)
    { chain: "tron", address: "0x6b5eafbcaf0e06d1a12c35e211263e3e51af767a", decimals: 6 }, // ERC20 PYUSD0 (lz:tron)
  ],
};

export default layerzeroConfig;
