// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Sky Dollar (usds)   Match: address=0xdc035d45d973e3ec169d2276ddab16f1e407384f   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset usds

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "avax", address: "0x86ff09db814ac346a7c6fe2cd648f27706d1d470", decimals: 18 }, // ERC20 USDS (lz:avalanche)
  ],
};

export default layerzeroConfig;
