// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Ethena USDe (ethena-usde)   Match: address=0x4c9edd5852cd905f086c759e8383e09bff1e68b3   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset ethena-usde

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "arbitrum", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:arbitrum)
    { chain: "avax", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:avalanche)
    { chain: "base", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:base)
    { chain: "berachain", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:bera)
    { chain: "blast", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:blast)
    { chain: "bsc", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:bsc)
    { chain: "era", address: "0x39fe7a0dacce31bd90418e3e659fb0b5f0b3db0d", decimals: 18 }, // NativeOFT USDe (lz:zksync)
    { chain: "fraxtal", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:fraxtal)
    { chain: "hyperliquid", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:hyperliquid)
    { chain: "ink", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:ink)
    { chain: "kava", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:kava)
    { chain: "linea", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:linea)
    { chain: "manta", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:manta)
    { chain: "mantle", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:mantle)
    { chain: "megaeth", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:megaeth)
    { chain: "metis", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:metis)
    { chain: "mode", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:mode)
    { chain: "optimism", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:optimism)
    { chain: "plasma", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:plasma)
    { chain: "scroll", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:scroll)
    { chain: "swellchain", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:swell)
    { chain: "xlayer", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:xlayer)
    { chain: "zircuit", address: "0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34", decimals: 18 }, // NativeOFT USDe (lz:zircuit)
  ],
};

export default layerzeroConfig;
