// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts
// Asset: EURC (euro-coin)   Source (auto-detected): ethereum
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts --asset euro-coin
// Registry: @hyperlane-xyz/registry@25.0.0

import type { HyperlaneConfig } from "../helper/bridgeConfig";

const hyperlaneConfig: HyperlaneConfig = {
  sourceChain: "ethereum",
  tokens: [
  ],
};

export default hyperlaneConfig;
