// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts
// Asset: EURC (euro-coin)
// Sources detected: (none)
// Registry: @wormhole-foundation/sdk-base@4.20.0
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts --asset euro-coin

import type { WormholeConfig } from "../helper/bridgeConfig";

const wormholeConfig: WormholeConfig = [
];

export default wormholeConfig;
