// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts
// Asset: Tether (tether)   Source (auto-detected): ethereum
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts --asset tether
// Registry: @hyperlane-xyz/registry@25.0.0

import type { HyperlaneConfig } from "../helper/bridgeConfig";

const hyperlaneConfig: HyperlaneConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "hyperliquid", address: "0xbF2D3b1a37D54ce86d0e1455884dA875a97C87a8", decimals: 6 }, // EvmHypSynthetic USDT
    { chain: "mantra", address: "0x680e8ECB908A2040232ef139A0A52cbE47b9F15B", decimals: 6 }, // EvmHypSynthetic USDT
    { chain: "polygon", address: "0xd9765D5fE176493808202e63E6B73b523D6A1C3A", decimals: 18 }, // EvmHypSynthetic USDT
    { chain: "swellchain", address: "0xb89c6ED617f5F46175E41551350725A09110bbCE", decimals: 6 }, // EvmHypSynthetic USDT
    { chain: "tomochain", address: "0x48083c69f5a42c6b69abbad48ae195bd36770ee2", decimals: 6 }, // EvmHypSynthetic USDT
  ],
};

export default hyperlaneConfig;
