// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts
// Asset: Tether (tether)
// Sources detected: ethereum
// Registry: @wormhole-foundation/sdk-base@4.20.0
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts --asset tether

import type { WormholeConfig } from "../helper/bridgeConfig";

const wormholeConfig: WormholeConfig = [
  {
    sourceChain: "ethereum",
    tokens: [
      { chain: "arbitrum", address: "0xE4728F3E48E94C6DA2B53610E677cc241DAFB134", decimals: 6 }, // USDT
      { chain: "avax", address: "0x9d228444FC4B7E15A2C481b48E10247A03351FD8", decimals: 6 }, // USDT
      { chain: "base", address: "0xFf0C62A4979400841eFaA6faADb07Ac7d5C98b27", decimals: 6 }, // USDT
      { chain: "bsc", address: "0x524bC91Dc82d6b90EF29F76A3ECAaBAffFD490Bc", decimals: 6 }, // USDT
      { chain: "moonbeam", address: "0xc30E9cA94CF52f3Bf5692aaCF81353a27052c46f", decimals: 6 }, // USDT
      { chain: "optimism", address: "0xf6B4185FCf8aF291c0E3927fbEab7046b4f6A8CA", decimals: 6 }, // USDT
      { chain: "polygon", address: "0x9417669fBF23357D2774e9D421307bd5eA1006d2", decimals: 6 }, // USDT
    ],
  },
];

export default wormholeConfig;
