// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Avalon USDa (usda-2)   Match: address=0x8a60e489004ca22d775c5f2c657598278d17d9c2   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset usda-2

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "avax", address: "0xc492fbae68ce6c5e14c7ed5cd8a59babd5c90e4c", decimals: 18 }, // NativeOFT USDA (lz:avalanche)
    { chain: "base", address: "0x1a42a30dcba20a22b69c40098d89cb7304f429b9", decimals: 18 }, // NativeOFT USDA (lz:base)
    { chain: "berachain", address: "0xff12470a969dd362eb6595ffb44c82c959fe9acc", decimals: 18 }, // NativeOFT USDa (lz:bera)
    { chain: "bsc", address: "0x9356086146be5158e98ad827e21b5cf944699894", decimals: 18 }, // NativeOFT USDa (lz:bsc)
    { chain: "mode", address: "0xc4df24680fe23ad109401a4a200de3994ad3c564", decimals: 18 }, // NativeOFT USDA (lz:mode)
  ],
};

export default layerzeroConfig;
