// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Re Protocol reUSD (re-protocol-reusd)   Match: address=0x5086bf358635b81d8c47c66d1c8b9e567db70c72   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset re-protocol-reusd

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "arbitrum", address: "0x76ce01f0ef25aa66cc5f1e546a005e4a63b25609", decimals: 18 }, // ERC20 reUSD (lz:arbitrum)
    { chain: "avax", address: "0x180af87b47bf272b2df59dccf2d76a6eafa625bf", decimals: 18 }, // ERC20 reUSD (lz:avalanche)
    { chain: "base", address: "0x7d214438d0f27afccc23b3d1e1a53906ace5cfea", decimals: 18 }, // ERC20 reUSD (lz:base)
    { chain: "bsc", address: "0xba9425ec55ee0e72216d18e0ad8bbba2553bfb60", decimals: 18 }, // ERC20 reUSD (lz:bsc)
    { chain: "ink", address: "0x5bcf6b008bf80b9296238546bace1797657b05d6", decimals: 18 }, // ERC20 reUSD (lz:ink)
    { chain: "katana", address: "0xe08853433fdbc504240455e295b644e0f44c3b29", decimals: 18 }, // ERC20 reUSD (lz:katana)
    { chain: "plasma", address: "0xe08853433fdbc504240455e295b644e0f44c3b29", decimals: 18 }, // ERC20 reUSD (lz:plasma)
  ],
};

export default layerzeroConfig;
