// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: fxUSD (f-x-protocol-fxusd)   Match: address=0x085780639cc2cacd35e474e71f4d000e2405d8f6   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset f-x-protocol-fxusd

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "base", address: "0x55380fe7a1910dff29a47b622057ab4139da42c5", decimals: 18 }, // NativeOFT fxUSD (lz:base)
  ],
};

export default layerzeroConfig;
