// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: Agora Dollar (agora-dollar)   Match: address=0x00000000efe302beaa2b3e6e1b18d08d69a9012a   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset agora-dollar

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "plasma", address: "0xecc5eafefbc2bd646cf8f707b5d280779e530169", decimals: 6 }, // ERC20 AUSD0 (lz:plasma)
  ],
};

export default layerzeroConfig;
