// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts
// Asset: USD Coin (usd-coin)   Source (auto-detected): ethereum
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateHyperlaneConfig.ts --asset usd-coin
// Registry: @hyperlane-xyz/registry@25.0.0

import type { HyperlaneConfig } from "../helper/bridgeConfig";

const hyperlaneConfig: HyperlaneConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "ink", address: "0x23f63C65c474f2A5BF80ea845Ca496Da3689A2B9", decimals: 6 }, // EvmHypSynthetic USDC
    { chain: "lisk", address: "0x0FC41a92F526A8CD22060A4052e156502D6B9db0", decimals: 6 }, // EvmHypSynthetic USDC
    { chain: "mantra", address: "0x5E76be0F4e09057D75140216F70fd4cE3365bb29", decimals: 6 }, // EvmHypSynthetic USDC
    { chain: "mode", address: "0xcA4b9B3b6Dae4E5Dc2D749b2bD400ef62E7ae642", decimals: 6 }, // EvmHypSynthetic USDC
    { chain: "optimism", address: "0x2DBe8c163f080b244D420be781abD37c1bfc51A6", decimals: 6 }, // EvmHypSynthetic USDC
    { chain: "polygon", address: "0xFDf46770Da4F907c09aEd92299552DC9c7996d99", decimals: 18 }, // EvmHypSynthetic USDC
    { chain: "pulse", address: "0xa5B0D537CeBE97f087Dc5FE5732d70719caaEc1D", decimals: 6 }, // EvmHypSynthetic USDC
    { chain: "tomochain", address: "0xbda330ea8f3005c421c8088e638fbb64fa71b9e0", decimals: 6 }, // EvmHypSynthetic USDC
  ],
};

export default hyperlaneConfig;
