// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts
// Asset: USD Coin (usd-coin)   Match: address=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48   Source (auto-detected): ethereum   Filter: auto (OFT wrappers + peggedTo=source)
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateLzConfig.ts --asset usd-coin

import type { LayerZeroConfig } from "../helper/bridgeConfig";

const layerzeroConfig: LayerZeroConfig = {
  sourceChain: "ethereum",
  tokens: [
    { chain: "0g", address: "0x8a2b28364102bea189d99a475c494330ef2bdd0b", decimals: 6 }, // HydraOFT USDC.e (lz:og)
    { chain: "abstract", address: "0x84a71ccd554cc1b02749b35d22f684cc8ec987e1", decimals: 6 }, // HydraOFT USDC.e (lz:abstract)
    { chain: "ap3x", address: "0x8a2b28364102bea189d99a475c494330ef2bdd0b", decimals: 6 }, // HydraOFT USDC.e (lz:apexfusionnexus)
    { chain: "apechain", address: "0xf1815bd50389c46847f0bda824ec8da914045d14", decimals: 6 }, // HydraOFT USDC.e (lz:ape)
    { chain: "arbitrum", address: "0xff970a61a04b1ca14834a43f5de4533ebddb5cc8", decimals: 6 }, // ERC20 USDC (lz:arbitrum)
    { chain: "berachain", address: "0x549943e04f40284185054145c6e4e9568c1d3241", decimals: 6 }, // HydraOFT USDC.e (lz:bera)
    { chain: "bsc", address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d", decimals: 18 }, // ERC20 USDC (lz:bsc)
    { chain: "btnx", address: "0x29ee6138dd4c9815f46d34a4a1ed48f46758a402", decimals: 6 }, // HydraOFT USDC.e (lz:botanix)
    { chain: "camp", address: "0x8a2b28364102bea189d99a475c494330ef2bdd0b", decimals: 6 }, // HydraOFT USDC.e (lz:camp)
    { chain: "citrea", address: "0xe045e6c36cf77faa2cfb54466d71a3aef7bbe839", decimals: 6 }, // ERC20 USDC (lz:citrea)
    { chain: "codex", address: "0xbba60da06c2c5424f03f7434542280fcad453d10", decimals: 6 }, // HydraOFT USDC (lz:codex)
    { chain: "cronos", address: "0xf951ec28187d9e5ca673da8fe6757e6f0be5f77c", decimals: 6 }, // HydraOFT USDC.e (lz:cronosevm)
    { chain: "degen", address: "0xf1815bd50389c46847f0bda824ec8da914045d14", decimals: 6 }, // HydraOFT USDC (lz:degen)
    { chain: "doma", address: "0x31eef89d5215c305304a2fa5376a1f1b6c5dc477", decimals: 6 }, // HydraOFT USDC.e (lz:doma)
    { chain: "edu_chain", address: "0x12a272a581fee5577a5dfa371afeb4b2f3a8c2f8", decimals: 6 }, // HydraOFT USDC.e (lz:edu)
    { chain: "fantom", address: "0x28a92dde19d9989f39a49905d7c9c2fac7799bdf", decimals: 6 }, // NativeOFT USDC (lz:fantom)
    { chain: "flare", address: "0xfbda5f676cb37624f28265a144a48b0d6e87d3b6", decimals: 6 }, // HydraOFT USDC.e (lz:flare)
    { chain: "flow", address: "0xf1815bd50389c46847f0bda824ec8da914045d14", decimals: 6 }, // HydraOFT USDC.e (lz:flow)
    { chain: "fuse", address: "0xc6bc407706b7140ee8eef2f86f9504651b63e7f9", decimals: 6 }, // HydraOFT USDC.e (lz:fuse)
    { chain: "gatelayer", address: "0x8a2b28364102bea189d99a475c494330ef2bdd0b", decimals: 6 }, // HydraOFT USDC.e (lz:gatelayer)
    { chain: "gensyn", address: "0x5b32c997211621d55a89cc5abaf1cc21f3a6ddf5", decimals: 6 }, // HydraOFT USDC.e (lz:gensyn)
    { chain: "glue", address: "0xee45ed3f6c675f319bb9de62991c1e78b484e0b8", decimals: 6 }, // HydraOFT USDC.e (lz:glue)
    { chain: "goat", address: "0x3022b87ac063de95b1570f46f5e470f8b53112d8", decimals: 6 }, // HydraOFT USDC.e (lz:goat)
    { chain: "gravity", address: "0xfbda5f676cb37624f28265a144a48b0d6e87d3b6", decimals: 6 }, // HydraOFT USDC.e (lz:gravity)
    { chain: "harmony", address: "0x44ced87b9f1492bf2dcf5c16004832569f7f6cba", decimals: 18 }, // ERC20 USDC (lz:harmony)
    { chain: "harmony", address: "0x9b5fae311a4a4b9d838f301c9c27b55d19baa4fb", decimals: 6 }, // ERC20 USDC (lz:harmony)
    { chain: "harmony", address: "0xbc594cabd205bd993e7ffa6f3e9cea75c1110da5", decimals: 6 }, // ERC20 USDC (lz:harmony)
    { chain: "hemi", address: "0xad11a8beb98bbf61dbb1aa0f6d6f2ecd87b35afa", decimals: 6 }, // HydraOFT USDC.e (lz:hemi)
    { chain: "horizen", address: "0xdf7108f8b10f9b9ec1aba01cca057268cbf86b6c", decimals: 6 }, // HydraOFT USDC.e (lz:horizen)
    { chain: "ink", address: "0xf1815bd50389c46847f0bda824ec8da914045d14", decimals: 6 }, // HydraOFT USDC.e (lz:ink)
    { chain: "iotaevm", address: "0xfbda5f676cb37624f28265a144a48b0d6e87d3b6", decimals: 6 }, // HydraOFT USDC.e (lz:iota)
    { chain: "klaytn", address: "0xe2053bcf56d2030d2470fb454574237cf9ee3d4b", decimals: 6 }, // HydraOFT USDC.e (lz:klaytn)
    { chain: "lightlink_phoenix", address: "0xbcf8c1b03bbdda88d579330bdf236b58f8bb2cfd", decimals: 6 }, // HydraOFT USDC.e (lz:lightlink)
    { chain: "moca", address: "0x9560abccafc1159a8772afef9ae85d455454a6aa", decimals: 6 }, // HydraOFT USDC.e (lz:moca)
    { chain: "nibiru", address: "0x0829f361a05d993d5ceb035ca6df3446b060970b", decimals: 6 }, // HydraOFT USDC.e (lz:nibiru)
    { chain: "orderly", address: "0xda6087e69c51e7d31b6dbad276a3c44703dfdcad", decimals: 6 }, // HydraOFT USDC.e (lz:orderly)
    { chain: "peaq", address: "0xbba60da06c2c5424f03f7434542280fcad453d10", decimals: 6 }, // HydraOFT USDC (lz:peaq)
    { chain: "plume_mainnet", address: "0x78add880a697070c1e765ac44d65323a0dcce913", decimals: 6 }, // HydraOFT USDC.e (lz:plumephoenix)
    { chain: "rari", address: "0xfbda5f676cb37624f28265a144a48b0d6e87d3b6", decimals: 6 }, // HydraOFT USDC.e (lz:rarible)
    { chain: "rbn", address: "0xe08ded898d7782b085cd240d7b234063696765ad", decimals: 6 }, // HydraOFT USDC.e (lz:redbelly)
    { chain: "rsk", address: "0x74c9f2b00581f1b11aa7ff05aa9f608b7389de67", decimals: 6 }, // HydraOFT USDC.e (lz:rootstock)
    { chain: "somnia", address: "0x28bec7e30e6faee657a03e19bf1128aad7632a00", decimals: 6 }, // HydraOFT USDC.e (lz:somnia)
    { chain: "spn", address: "0x6c030c5cc283f791b26816f325b9c632d964f8a1", decimals: 6 }, // HydraOFT USDC.e (lz:superposition)
    { chain: "stable", address: "0x8a2b28364102bea189d99a475c494330ef2bdd0b", decimals: 6 }, // HydraOFT USDC.e (lz:stable)
    { chain: "sty", address: "0xf1815bd50389c46847f0bda824ec8da914045d14", decimals: 6 }, // HydraOFT USDC.e (lz:story)
    { chain: "taiko", address: "0x19e26b0638bf63aa9fa4d14c6baf8d52ebe86c5c", decimals: 6 }, // HydraOFT USDC.e (lz:taiko)
    { chain: "telos", address: "0xf1815bd50389c46847f0bda824ec8da914045d14", decimals: 6 }, // HydraOFT USDC.e (lz:telos)
    { chain: "tempo", address: "0x20c000000000000000000000b9537d11c60e8b50", decimals: 6 }, // HydraOFT USDC.e (lz:tempo)
    { chain: "vana", address: "0xf1815bd50389c46847f0bda824ec8da914045d14", decimals: 6 }, // HydraOFT USDC.e (lz:islander)
    { chain: "xc", address: "0xfbda5f676cb37624f28265a144a48b0d6e87d3b6", decimals: 6 }, // HydraOFT USDC (lz:xchain)
    { chain: "xdc", address: "0xcc0587aebda397146cc828b445db130a94486e74", decimals: 6 }, // HydraOFT USDC.e (lz:xdc)
  ],
};

export default layerzeroConfig;
