// Auto-generated by src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts
// Asset: USD Coin (usd-coin)
// Sources detected: arbitrum, avax, base, bsc, ethereum, optimism, polygon, solana
// Registry: @wormhole-foundation/sdk-base@4.20.0
// Re-run: ts-node src/adapters/peggedAssets/helper/scripts/generateWormholeConfig.ts --asset usd-coin

import type { WormholeConfig } from "../helper/bridgeConfig";

const wormholeConfig: WormholeConfig = [
  {
    sourceChain: "arbitrum",
    tokens: [
      { chain: "avax", address: "0x4b5fE357Eb11c735078e47526D6e853DBff18541", decimals: 6 }, // USDC
      { chain: "base", address: "0xb96B82Cd6D45d98Fb6897D16A5E4EE888329C513", decimals: 6 }, // USDC
      { chain: "bsc", address: "0x5caa170b465122D15a6D20FD9A804a9613CE7882", decimals: 6 }, // USDC
      { chain: "celo", address: "0xA41a62567d9eb960D84b72663FdaeBE0BCdE2683", decimals: 6 }, // USDC
      { chain: "ethereum", address: "0xCFc006a32a98031C2338BF9d5ff8ED2c0Cae4a9e", decimals: 6 }, // USDC
      { chain: "optimism", address: "0xa6252F56cc6eEA21165d56744C795F91c8a3Cf68", decimals: 6 }, // USDC
      { chain: "polygon", address: "0x7800FE8951cdc1cDea748d878fAce63018D97960", decimals: 6 }, // USDC
    ],
  },
  {
    sourceChain: "avax",
    tokens: [
      { chain: "arbitrum", address: "0x93e0FcbEd43CD6fC30DF00CcBD4669718dc74e77", decimals: 6 }, // USDC
      { chain: "base", address: "0xD83385fE100E20c269a5975D4Bf92525BcE09F87", decimals: 6 }, // USDC
      { chain: "bsc", address: "0xc88Dc63bf0c8c8198C97Db0945E3eF25Ca89A8e4", decimals: 6 }, // USDC
      { chain: "celo", address: "0x62FFf2D2D1692D52eAf043AeeC727F7918d269D3", decimals: 6 }, // USDC
      { chain: "ethereum", address: "0x39EbF69137D98FB7659Ef8D4ea21ec26394389d7", decimals: 6 }, // USDC
      { chain: "moonbeam", address: "0xd4918c40cA9f02d42Cb53d06587aF42017Bc345D", decimals: 6 }, // USDC
      { chain: "optimism", address: "0x355f0a8a7ecAeD971b8Fbd50994558291ff2413a", decimals: 6 }, // USDC
      { chain: "polygon", address: "0xAEA5CC14DefbC1b845FDE729E563B717Ee6825ae", decimals: 6 }, // USDC
    ],
  },
  {
    sourceChain: "base",
    tokens: [
      { chain: "arbitrum", address: "0x8619F97D4d08382548F536E5CE1D3e0D9bA40326", decimals: 6 }, // USDC
      { chain: "avax", address: "0xab933e939a9236BD439F7d29b87CE712f42bAC06", decimals: 6 }, // USDC
      { chain: "bsc", address: "0x55CaD531c8E303Cab8B3BE4bB4744Db4f896ac81", decimals: 6 }, // USDC
      { chain: "celo", address: "0x2e2acb1782Aad0490f8446b6fD4626C467987bD6", decimals: 6 }, // USDC
      { chain: "moonbeam", address: "0xE6d02a875CcC153c076fe418f33De3A5C420f505", decimals: 6 }, // USDC
      { chain: "optimism", address: "0xb931c7BbD87A6e249EaA7355B13927F9c99Bce87", decimals: 6 }, // USDC
      { chain: "polygon", address: "0x1eeCaB0F75fE93abbFa0cDFfb4fB13d1dC8706c8", decimals: 6 }, // USDC
    ],
  },
  {
    sourceChain: "bsc",
    tokens: [
      { chain: "arbitrum", address: "0x1a0590F951bc9C3818Ce75ba5Bbe92831b2cf57e", decimals: 18 }, // USDC
      { chain: "avax", address: "0x6145E8a910aE937913426BF32De2b26039728ACF", decimals: 18 }, // USDC
      { chain: "base", address: "0x68E2b07F92ed506f92935d7359ECA84D5342dbb4", decimals: 18 }, // USDC
      { chain: "celo", address: "0x9d9abAE97a9344e3854527b4efbB366a1564bfEb", decimals: 18 }, // USDC
      { chain: "ethereum", address: "0x7cd167B101D2808Cfd2C45d17b2E7EA9F46b74B6", decimals: 18 }, // USDC
      { chain: "moonbeam", address: "0x7f433E22366E03a3758CE22cCf82887d828078f8", decimals: 18 }, // USDC
      { chain: "optimism", address: "0x1C15057d1F3794C934a6cBC1f7EceE934050F219", decimals: 18 }, // USDC
      { chain: "polygon", address: "0x4B3a922c773BDCF3BA8f1A4FDAc2029E1D0E9868", decimals: 18 }, // USDC
    ],
  },
  {
    sourceChain: "ethereum",
    tokens: [
      { chain: "arbitrum", address: "0xC96F2715E2a242d50D1b0bC923dbe1740b8eCf18", decimals: 6 }, // USDC
      { chain: "avax", address: "0xB24CA28D4e2742907115fECda335b40dbda07a4C", decimals: 6 }, // USDC
      { chain: "base", address: "0xec267C53f53807c2337C257f8AC3Fc3cC07cc0ed", decimals: 6 }, // USDC
      { chain: "bsc", address: "0xB04906e95AB5D797aDA81508115611fee694c2b3", decimals: 6 }, // USDC
      { chain: "celo", address: "0x37f750B7cC259A2f741AF45294f6a16572CF5cAd", decimals: 6 }, // USDC
      { chain: "moonbeam", address: "0x931715FEE2d06333043d11F658C8CE934aC61D0c", decimals: 6 }, // USDC
      { chain: "optimism", address: "0x711e53D031ea9B0bb0C24dD506df11b41AEA419e", decimals: 6 }, // USDC
      { chain: "polygon", address: "0x4318CB63A2b8edf2De971E2F17F77097e499459D", decimals: 6 }, // USDC
    ],
  },
  {
    sourceChain: "optimism",
    tokens: [
      { chain: "arbitrum", address: "0x3A5C2Da9E30741cb59a5e9446A23A86886fC9DC2", decimals: 6 }, // USDC
      { chain: "avax", address: "0xBe04f76A0ba2100c3F2d6Aa1FD8484F415469573", decimals: 6 }, // USDC
      { chain: "base", address: "0xc6bfBeb3002aD563D2d1f72614C61C83Bf147Acd", decimals: 6 }, // USDC
      { chain: "bsc", address: "0xa41ae127D04F7ee73B5058E2C60Fb7c7A2D21F79", decimals: 6 }, // USDC
      { chain: "celo", address: "0xEe48963C003e21EaCEdFA8a0A19BB3cbF7E776Fe", decimals: 6 }, // USDC
      { chain: "moonbeam", address: "0x7143e8EA96e158381057a58AfdDF44601c7e532C", decimals: 6 }, // USDC
      { chain: "polygon", address: "0x31F12aCb60C3c32EE884F3894a873347C097D925", decimals: 6 }, // USDC
    ],
  },
  {
    sourceChain: "polygon",
    tokens: [
      { chain: "arbitrum", address: "0x599ADB10E6A012dF34935D47407450f6D7170e3C", decimals: 6 }, // USDC
      { chain: "avax", address: "0xDb2d08f5A9C9ADBBA0DE5a69bbB1E9Ca03411692", decimals: 6 }, // USDC
      { chain: "base", address: "0xFe1579BAc60363c8572CB30Bf4DD1Fd85811BBF8", decimals: 6 }, // USDC
      { chain: "bsc", address: "0xe6d82Bbe75041E42E51d755e922cE1BA91af9c4d", decimals: 6 }, // USDC
      { chain: "celo", address: "0x42c76808f3179A091Ee007A2955aF2522978ADE7", decimals: 6 }, // USDC
      { chain: "moonbeam", address: "0x4415BfBDee669446550d55c749007EF60B520FC8", decimals: 6 }, // USDC
      { chain: "optimism", address: "0xbB1EaB9Eb8fDf65F0E291D013DA07B4b65a27a01", decimals: 6 }, // USDC
    ],
  },
  {
    sourceChain: "solana",
    tokens: [
      { chain: "arbitrum", address: "0x3870546cfd600ba87e4180686d29dC993A45d3B7", decimals: 6 }, // USDC
      { chain: "avax", address: "0x0950Fc1AD509358dAeaD5eB8020a3c7d8b43b9DA", decimals: 6 }, // USDC
      { chain: "base", address: "0xe8CE40EBBB844142400D21558a2F1c9683d69139", decimals: 6 }, // USDC
      { chain: "bsc", address: "0x91Ca579B0D47E5cfD5D0862c21D5659d39C8eCf0", decimals: 6 }, // USDC
      { chain: "celo", address: "0x8B6eef6C449D3Ac723a9C06a9eaE2dCd7d308BA9", decimals: 6 }, // USDC
      { chain: "ethereum", address: "0x41f7B8b9b897276b7AAE926a9016935280b44E97", decimals: 6 }, // USDC
      { chain: "moonbeam", address: "0x098d6eE48341D6a0a0A72dE5baaF80A10E0F6082", decimals: 6 }, // USDC
      { chain: "optimism", address: "0x6F974A6dfD5B166731704Be226795901c45Bb815", decimals: 6 }, // USDC
      { chain: "polygon", address: "0x576Cf361711cd940CD9C397BB98C4C896cBd38De", decimals: 6 }, // USDC
    ],
  },
];

export default wormholeConfig;
